---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE EXT FOLDER.
--- 
local global = _G
local ipairs = global.ipairs
local DatabaseUtils = require("forgeutils.internal.database.databaseutils")

local logger = require("forgeutils.logger").Get("Audio")

---@class forgeutils.internal.database.Audio
--- Note: Autogenerated!
--- This is a generated lua binding layer for the Audio database.
local Audio = {}

---@private
--- This method is called after data is merged
Audio.InsertToDBs = function()
    Audio.BindPreparedStatements()
end

Audio.tPreparedStatements = {
    "Audio_AmbienceCategories", 
    "Audio_AmbienceEventToCategoryMap", 
    "Audio_Categories", 
    "Audio_CoasterMusicEventToCategoryMap", 
    "Audio_CoasterMusicEvents", 
    "Audio_ContentPacks", 
    "Audio_DiegeticMusicEventToCategoryMap", 
    "Audio_DiegeticMusicEvents", 
    "Audio_EventToCategoryMap", 
    "Audio_FlatrideMusicEventToCategoryMap", 
    "Audio_FlatrideMusicEvents", 
    "Audio_GunSoundCategories", 
    "Audio_GunSoundEventToCategoryMap", 
    "Audio_GunSoundEvents", 
    "Audio_MusicCategories", 
    "Audio_PlaceableAmbienceEvents", 
    "Audio_PlaceableTriggeredEvents", 
    "Audio_SpeakerMusicEventToCategoryMap", 
    "Audio_SpeakerMusicEvents"
}

---@private
function Audio.BindPreparedStatements()
    logger:DebugQuery("BindPreparedStatements()")
    for _, filename in ipairs(Audio.tPreparedStatements) do
        DatabaseUtils.BindPreparedStatement("Audio", filename)
    end
end


--- Note: Autogenerated.
--- Inserter for table AmbienceCategories.
---@param Name string Common Values = "Aquatic", "Electronic", "Fairytale", "GreekMythos", "Legacy". 
function Audio.AmbienceCategories__Insert(Name)
    DatabaseUtils.ExecuteQuery("Audio", "AmbienceCategories__Insert", {Name}, 1)
end

--- Note: Autogenerated.
--- Updates field "TextSymbol" in AmbienceCategories. Common Values = "Music_Heading_Aquatic", "Music_Heading_Electronic", "Music_Heading_Fairytale", "Music_Heading_GreekMythos", "Music_Heading_Legacy". 
---@param Name string Common Values = "Aquatic", "Electronic", "Fairytale", "GreekMythos", "Legacy".  (Lookup Key)
---@param TextSymbol string|nil Common Values = "Music_Heading_Aquatic", "Music_Heading_Electronic", "Music_Heading_Fairytale", "Music_Heading_GreekMythos", "Music_Heading_Legacy". 
function Audio.AmbienceCategories__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("Audio", "AmbienceCategories__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
--- Inserter for table AmbienceEventToCategoryMap.
---@param EventName string Common Values = "AMB_Bat_Cave", "AMB_Baths", "AMB_Battlefield", "AMB_Bewitched_Forest", "AMB_BubblyUnderwater". 
---@param Category string Common Values = "Fairytale", "Sorcery", "Pirate", "ToyBox", "GreekMythos". 
function Audio.AmbienceEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "AmbienceEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Updates field "Category" in AmbienceEventToCategoryMap. Common Values = "Fairytale", "Sorcery", "Pirate", "ToyBox", "GreekMythos". 
---@param EventName string Common Values = "AMB_Bat_Cave", "AMB_Baths", "AMB_Battlefield", "AMB_Bewitched_Forest", "AMB_BubblyUnderwater".  (Lookup Key)
---@param Category string Common Values = "Fairytale", "Sorcery", "Pirate", "ToyBox", "GreekMythos". 
function Audio.AmbienceEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "AmbienceEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Inserter for table Categories.
---@param Name string Common Values = "Alarms", "Announcement", "Aquatic", "Creatures", "Electronic". 
function Audio.Categories__Insert(Name)
    DatabaseUtils.ExecuteQuery("Audio", "Categories__Insert", {Name}, 1)
end

--- Note: Autogenerated.
--- Updates field "TextSymbol" in Categories. Common Values = "TriggeredSFX_Alarms_Heading", "TriggeredSFX_Announcement_Heading", "TriggeredSFX_Aquatic_Heading", "TriggeredSFX_Creatures_Heading", "TriggeredSFX_Electronic_Heading". 
---@param Name string Common Values = "Alarms", "Announcement", "Aquatic", "Creatures", "Electronic".  (Lookup Key)
---@param TextSymbol string|nil Common Values = "TriggeredSFX_Alarms_Heading", "TriggeredSFX_Announcement_Heading", "TriggeredSFX_Aquatic_Heading", "TriggeredSFX_Creatures_Heading", "TriggeredSFX_Electronic_Heading". 
function Audio.Categories__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("Audio", "Categories__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
--- Inserter for table CoasterMusicEventToCategoryMap.
---@param EventName string 
---@param Category string 
function Audio.CoasterMusicEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "CoasterMusicEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Updates field "Category" in CoasterMusicEventToCategoryMap. 
---@param EventName string  (Lookup Key)
---@param Category string 
function Audio.CoasterMusicEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "CoasterMusicEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Inserter for table CoasterMusicEvents.
---@param EventName string 
function Audio.CoasterMusicEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("Audio", "CoasterMusicEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
--- Updates field "ContentPack" in CoasterMusicEvents. Default = "BaseGame". 
---@param EventName string  (Lookup Key)
---@param ContentPack string Default = "BaseGame". 
function Audio.CoasterMusicEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("Audio", "CoasterMusicEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
--- Inserter for table ContentPacks.
---@param Name string Common Values = "BaseGame", "Deluxe", "PDLC1", "PDLC2", "PDLC3". 
---@param EnumValue integer Common Values = 0, 1, 2, 4, 8. 
function Audio.ContentPacks__Insert(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("Audio", "ContentPacks__Insert", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Updates field "EnumValue" in ContentPacks. Common Values = 0, 1, 2, 4, 8. 
---@param Name string Common Values = "BaseGame", "Deluxe", "PDLC1", "PDLC2", "PDLC3".  (Lookup Key)
---@param EnumValue integer Common Values = 0, 1, 2, 4, 8. 
function Audio.ContentPacks__Update__EnumValue(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("Audio", "ContentPacks__Update__EnumValue", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Inserter for table DiegeticMusicEventToCategoryMap.
---@param EventName string Common Values = "Aqua_01", "Aqua_02", "Aqua_03", "Aqua_04", "Aqua_05". 
---@param Category string Common Values = "Playlists", "Legacy", "Pirate", "Fairytale", "Orchestral". 
function Audio.DiegeticMusicEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "DiegeticMusicEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Updates field "Category" in DiegeticMusicEventToCategoryMap. Common Values = "Playlists", "Legacy", "Pirate", "Fairytale", "Orchestral". 
---@param EventName string Common Values = "Aqua_01", "Aqua_02", "Aqua_03", "Aqua_04", "Aqua_05".  (Lookup Key)
---@param Category string Common Values = "Playlists", "Legacy", "Pirate", "Fairytale", "Orchestral". 
function Audio.DiegeticMusicEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "DiegeticMusicEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Inserter for table DiegeticMusicEvents.
---@param EventName string Common Values = "Aqua_01", "Aqua_02", "Aqua_03", "Aqua_04", "Aqua_05". 
function Audio.DiegeticMusicEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("Audio", "DiegeticMusicEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
--- Updates field "ContentPack" in DiegeticMusicEvents. Default = "BaseGame". Common Values = "BaseGame", "PDLC2", "PDLC3". 
---@param EventName string Common Values = "Aqua_01", "Aqua_02", "Aqua_03", "Aqua_04", "Aqua_05".  (Lookup Key)
---@param ContentPack string Default = "BaseGame". Common Values = "BaseGame", "PDLC2", "PDLC3". 
function Audio.DiegeticMusicEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("Audio", "DiegeticMusicEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
--- Inserter for table EventToCategoryMap.
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken". 
---@param Category string Common Values = "Musical", "Legacy", "SciFi", "GreekMythos", "Viking". 
function Audio.EventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "EventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Updates field "Category" in EventToCategoryMap. Common Values = "Musical", "Legacy", "SciFi", "GreekMythos", "Viking". 
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken".  (Lookup Key)
---@param Category string Common Values = "Musical", "Legacy", "SciFi", "GreekMythos", "Viking". 
function Audio.EventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "EventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Inserter for table FlatrideMusicEventToCategoryMap.
---@param EventName string 
---@param Category string 
function Audio.FlatrideMusicEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "FlatrideMusicEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Updates field "Category" in FlatrideMusicEventToCategoryMap. 
---@param EventName string  (Lookup Key)
---@param Category string 
function Audio.FlatrideMusicEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "FlatrideMusicEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Inserter for table FlatrideMusicEvents.
---@param EventName string Common Values = "BehemothSwing360", "BumperCarMedley", "CLD", "CSL", "Chairoplane". 
function Audio.FlatrideMusicEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("Audio", "FlatrideMusicEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
--- Updates field "ContentPack" in FlatrideMusicEvents. Default = "BaseGame". Common Values = "BaseGame". 
---@param EventName string Common Values = "BehemothSwing360", "BumperCarMedley", "CLD", "CSL", "Chairoplane".  (Lookup Key)
---@param ContentPack string Default = "BaseGame". Common Values = "BaseGame". 
function Audio.FlatrideMusicEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("Audio", "FlatrideMusicEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
--- Inserter for table GunSoundCategories.
---@param Name string|nil Common Values = "Aquatic", "Fairytale", "GreekMythos", "Resort", "SciFi". 
---@param TextSymbol string|nil Common Values = "Music_Heading_Aquatic", "Music_Heading_Fairytale", "Music_Heading_GreekMythos", "Music_Heading_Resort", "Music_Heading_SciFi". 
function Audio.GunSoundCategories__Insert(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("Audio", "GunSoundCategories__Insert", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
--- Updates field "TextSymbol" in GunSoundCategories. Common Values = "Music_Heading_Aquatic", "Music_Heading_Fairytale", "Music_Heading_GreekMythos", "Music_Heading_Resort", "Music_Heading_SciFi". 
---@param Name string|nil Common Values = "Aquatic", "Fairytale", "GreekMythos", "Resort", "SciFi".  (Lookup Key)
---@param TextSymbol string|nil Common Values = "Music_Heading_Aquatic", "Music_Heading_Fairytale", "Music_Heading_GreekMythos", "Music_Heading_Resort", "Music_Heading_SciFi". 
function Audio.GunSoundCategories__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("Audio", "GunSoundCategories__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
--- Inserter for table GunSoundEventToCategoryMap.
---@param EventName string|nil Common Values = "SHT_Aquatic", "SHT_Arcade", "SHT_Fairytale", "SHT_Mythology", "SHT_Resort". 
---@param Category string|nil Common Values = "Aquatic", "Fairytale", "GreekMythos", "Resort", "SciFi". 
function Audio.GunSoundEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "GunSoundEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Updates field "Category" in GunSoundEventToCategoryMap. Common Values = "Aquatic", "Fairytale", "GreekMythos", "Resort", "SciFi". 
---@param EventName string|nil Common Values = "SHT_Aquatic", "SHT_Arcade", "SHT_Fairytale", "SHT_Mythology", "SHT_Resort".  (Lookup Key)
---@param Category string|nil Common Values = "Aquatic", "Fairytale", "GreekMythos", "Resort", "SciFi". 
function Audio.GunSoundEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "GunSoundEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Inserter for table GunSoundEvents.
---@param EventName string|nil Common Values = "SHT_Aquatic", "SHT_Arcade", "SHT_Fairytale", "SHT_Mythology", "SHT_Resort". 
---@param ContentPack string|nil Common Values = "BaseGame". 
function Audio.GunSoundEvents__Insert(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("Audio", "GunSoundEvents__Insert", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
--- Updates field "ContentPack" in GunSoundEvents. Common Values = "BaseGame". 
---@param EventName string|nil Common Values = "SHT_Aquatic", "SHT_Arcade", "SHT_Fairytale", "SHT_Mythology", "SHT_Resort".  (Lookup Key)
---@param ContentPack string|nil Common Values = "BaseGame". 
function Audio.GunSoundEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("Audio", "GunSoundEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
--- Inserter for table MusicCategories.
---@param Name string Common Values = "Aquatic", "Electronic", "Fairytale", "Festive", "GreekMythos". 
function Audio.MusicCategories__Insert(Name)
    DatabaseUtils.ExecuteQuery("Audio", "MusicCategories__Insert", {Name}, 1)
end

--- Note: Autogenerated.
--- Updates field "TextSymbol" in MusicCategories. Common Values = "Music_Heading_Aquatic", "Music_Heading_Electronic", "Music_Heading_Fairytale", "Music_Heading_Festive", "Music_Heading_GreekMythos". 
---@param Name string Common Values = "Aquatic", "Electronic", "Fairytale", "Festive", "GreekMythos".  (Lookup Key)
---@param TextSymbol string|nil Common Values = "Music_Heading_Aquatic", "Music_Heading_Electronic", "Music_Heading_Fairytale", "Music_Heading_Festive", "Music_Heading_GreekMythos". 
function Audio.MusicCategories__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("Audio", "MusicCategories__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
--- Inserter for table PlaceableAmbienceEvents.
---@param EventName string Common Values = "AMB_Bat_Cave", "AMB_Baths", "AMB_Battlefield", "AMB_Bewitched_Forest", "AMB_BubblyUnderwater". 
function Audio.PlaceableAmbienceEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("Audio", "PlaceableAmbienceEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
--- Updates field "ContentPack" in PlaceableAmbienceEvents. Default = "BaseGame". Common Values = "BaseGame", "PDLC2", "PDLC3". 
---@param EventName string Common Values = "AMB_Bat_Cave", "AMB_Baths", "AMB_Battlefield", "AMB_Bewitched_Forest", "AMB_BubblyUnderwater".  (Lookup Key)
---@param ContentPack string Default = "BaseGame". Common Values = "BaseGame", "PDLC2", "PDLC3". 
function Audio.PlaceableAmbienceEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("Audio", "PlaceableAmbienceEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
--- Inserter for table PlaceableTriggeredEvents.
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken". 
function Audio.PlaceableTriggeredEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("Audio", "PlaceableTriggeredEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
--- Updates field "ContentPack" in PlaceableTriggeredEvents. Default = "BaseGame". Common Values = "BaseGame", "PDLC3", "PDLC2". 
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken".  (Lookup Key)
---@param ContentPack string Default = "BaseGame". Common Values = "BaseGame", "PDLC3", "PDLC2". 
function Audio.PlaceableTriggeredEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("Audio", "PlaceableTriggeredEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
--- Updates field "SupportsPitchShift" in PlaceableTriggeredEvents. Default = "0". Common Values = 1. 
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken".  (Lookup Key)
---@param SupportsPitchShift boolean Default = "0". Common Values = 1. 
function Audio.PlaceableTriggeredEvents__Update__SupportsPitchShift(EventName, SupportsPitchShift)
    DatabaseUtils.ExecuteQuery("Audio", "PlaceableTriggeredEvents__Update__SupportsPitchShift", {EventName, SupportsPitchShift}, 2)
end

--- Note: Autogenerated.
--- Inserter for table SpeakerMusicEventToCategoryMap.
---@param EventName string 
---@param Category string 
function Audio.SpeakerMusicEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "SpeakerMusicEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Updates field "Category" in SpeakerMusicEventToCategoryMap. 
---@param EventName string  (Lookup Key)
---@param Category string 
function Audio.SpeakerMusicEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("Audio", "SpeakerMusicEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
--- Inserter for table SpeakerMusicEvents.
---@param EventName string 
function Audio.SpeakerMusicEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("Audio", "SpeakerMusicEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
--- Updates field "ContentPack" in SpeakerMusicEvents. Default = "BaseGame". 
---@param EventName string  (Lookup Key)
---@param ContentPack string Default = "BaseGame". 
function Audio.SpeakerMusicEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("Audio", "SpeakerMusicEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end


return Audio
