---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE EXT FOLDER.
--- 
local global = _G
local ipairs = global.ipairs
local DatabaseUtils = require("forgeutils.internal.database.databaseutils")

local logger = require("forgeutils.logger").Get("ModularScenery")

---@class forgeutils.internal.database.ModularScenery
--- Note: Autogenerated!
--- This is a generated lua binding layer for the ModularScenery database.
local ModularScenery = {}

---@private
--- This method is called after data is merged
ModularScenery.InsertToDBs = function()
    ModularScenery.BindPreparedStatements()
end

ModularScenery.tPreparedStatements = {
    "ModularScenery_Audio", 
    "ModularScenery_Blueprint_Tags", 
    "ModularScenery_BrowserCategories", 
    "ModularScenery_BrowserFilters", 
    "ModularScenery_ComplexTypes", 
    "ModularScenery_ContentPacks", 
    "ModularScenery_DevTransitionList", 
    "ModularScenery_FacilityProps", 
    "ModularScenery_FireworkEffects", 
    "ModularScenery_GridProps", 
    "ModularScenery_LocalGridAlignmentStyle", 
    "ModularScenery_Metadata_Tags", 
    "ModularScenery_ModularSceneryParts", 
    "ModularScenery_PartComplexMembers", 
    "ModularScenery_PartControlPoints", 
    "ModularScenery_PartCustomFilterIDs", 
    "ModularScenery_PartDataPrefabs", 
    "ModularScenery_PathExtraProps", 
    "ModularScenery_PathExtraSnapType", 
    "ModularScenery_PathProps", 
    "ModularScenery_SceneryScaling", 
    "ModularScenery_Simulation", 
    "ModularScenery_SnapEdgePartData", 
    "ModularScenery_TagGroups", 
    "ModularScenery_TagGroupsDefinition", 
    "ModularScenery_TagGroupsToBrowserTabs", 
    "ModularScenery_TagSet", 
    "ModularScenery_ThemeNames", 
    "ModularScenery_Theming", 
    "ModularScenery_TriggerTargetProps", 
    "ModularScenery_UIData", 
    "ModularScenery_UIPartOrdering", 
    "ModularScenery_UtilityConnection", 
    "ModularScenery_UtilityConsumer", 
    "ModularScenery_UtilityDistribution", 
    "ModularScenery_UtilityProduction", 
    "ModularScenery_UtilityTypes", 
    "ModularScenery_WaterCleanliness"
}

---@private
function ModularScenery.BindPreparedStatements()
    logger:DebugQuery("BindPreparedStatements()")
    for _, filename in ipairs(ModularScenery.tPreparedStatements) do
        DatabaseUtils.BindPreparedStatement("ModularScenery", filename)
    end
end


--- Note: Autogenerated.
--- Inserter for table Audio.
---@param SceneryPartName string Common Values = "RR_GuestSpawnPoint". 
function ModularScenery.Audio__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Audio__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
--- Updates field "PlacementSound" in Audio. Default = "Default_Placement_Sound". Common Values = "Default_Placement_Sound". 
---@param SceneryPartName string Common Values = "RR_GuestSpawnPoint".  (Lookup Key)
---@param PlacementSound string|nil Default = "Default_Placement_Sound". Common Values = "Default_Placement_Sound". 
function ModularScenery.Audio__Update__PlacementSound(SceneryPartName, PlacementSound)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Audio__Update__PlacementSound", {SceneryPartName, PlacementSound}, 2)
end

--- Note: Autogenerated.
--- Updates field "DeletionSound" in Audio. Default = "Default_Deletion_Sound". Common Values = "Default_Deletion_Sound". 
---@param SceneryPartName string Common Values = "RR_GuestSpawnPoint".  (Lookup Key)
---@param DeletionSound string|nil Default = "Default_Deletion_Sound". Common Values = "Default_Deletion_Sound". 
function ModularScenery.Audio__Update__DeletionSound(SceneryPartName, DeletionSound)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Audio__Update__DeletionSound", {SceneryPartName, DeletionSound}, 2)
end

--- Note: Autogenerated.
--- Updates field "MoveSound" in Audio. Default = "Default_Move_Sound". Common Values = "Default_Move_Sound". 
---@param SceneryPartName string Common Values = "RR_GuestSpawnPoint".  (Lookup Key)
---@param MoveSound string|nil Default = "Default_Move_Sound". Common Values = "Default_Move_Sound". 
function ModularScenery.Audio__Update__MoveSound(SceneryPartName, MoveSound)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Audio__Update__MoveSound", {SceneryPartName, MoveSound}, 2)
end

--- Note: Autogenerated.
--- Updates field "GlassComposition" in Audio. Default = "0". Common Values = 0.0. 
---@param SceneryPartName string Common Values = "RR_GuestSpawnPoint".  (Lookup Key)
---@param GlassComposition number|nil Default = "0". Common Values = 0.0. 
function ModularScenery.Audio__Update__GlassComposition(SceneryPartName, GlassComposition)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Audio__Update__GlassComposition", {SceneryPartName, GlassComposition}, 2)
end

--- Note: Autogenerated.
--- Updates field "MetalComposition" in Audio. Default = "0". Common Values = 0.0. 
---@param SceneryPartName string Common Values = "RR_GuestSpawnPoint".  (Lookup Key)
---@param MetalComposition number|nil Default = "0". Common Values = 0.0. 
function ModularScenery.Audio__Update__MetalComposition(SceneryPartName, MetalComposition)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Audio__Update__MetalComposition", {SceneryPartName, MetalComposition}, 2)
end

--- Note: Autogenerated.
--- Updates field "PlasticComposition" in Audio. Default = "0". Common Values = 0.0. 
---@param SceneryPartName string Common Values = "RR_GuestSpawnPoint".  (Lookup Key)
---@param PlasticComposition number|nil Default = "0". Common Values = 0.0. 
function ModularScenery.Audio__Update__PlasticComposition(SceneryPartName, PlasticComposition)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Audio__Update__PlasticComposition", {SceneryPartName, PlasticComposition}, 2)
end

--- Note: Autogenerated.
--- Updates field "StoneComposition" in Audio. Default = "0". Common Values = 0.0. 
---@param SceneryPartName string Common Values = "RR_GuestSpawnPoint".  (Lookup Key)
---@param StoneComposition number|nil Default = "0". Common Values = 0.0. 
function ModularScenery.Audio__Update__StoneComposition(SceneryPartName, StoneComposition)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Audio__Update__StoneComposition", {SceneryPartName, StoneComposition}, 2)
end

--- Note: Autogenerated.
--- Updates field "WoodComposition" in Audio. Default = "0". Common Values = 0.0. 
---@param SceneryPartName string Common Values = "RR_GuestSpawnPoint".  (Lookup Key)
---@param WoodComposition number|nil Default = "0". Common Values = 0.0. 
function ModularScenery.Audio__Update__WoodComposition(SceneryPartName, WoodComposition)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Audio__Update__WoodComposition", {SceneryPartName, WoodComposition}, 2)
end

--- Note: Autogenerated.
--- Inserter for table Blueprint_Tags.
---@param SceneryPart string Common Values = "NAT_Aquatic_WaterLily_Common_01", "NAT_Aquatic_WaterLily_Common_02", "NAT_Aquatic_WaterLily_Common_03", "NAT_Aquatic_WaterLily_Common_04", "Facility_Shops_PhotoKiosk". 
---@param Tag string Common Values = "Filter_Theme_PlanetCoaster", "Filter_Theme_Fairytale", "Filter_Theme_Resort", "Filter_PDLC_Toybox", "Filter_Theme_Toybox". 
function ModularScenery.Blueprint_Tags__Insert(SceneryPart, Tag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Blueprint_Tags__Insert", {SceneryPart, Tag}, 2)
end

--- Note: Autogenerated.
--- Updates field "Tag" in Blueprint_Tags. Common Values = "Filter_Theme_PlanetCoaster", "Filter_Theme_Fairytale", "Filter_Theme_Resort", "Filter_PDLC_Toybox", "Filter_Theme_Toybox". 
---@param SceneryPart string Common Values = "NAT_Aquatic_WaterLily_Common_01", "NAT_Aquatic_WaterLily_Common_02", "NAT_Aquatic_WaterLily_Common_03", "NAT_Aquatic_WaterLily_Common_04", "Facility_Shops_PhotoKiosk".  (Lookup Key)
---@param Tag string Common Values = "Filter_Theme_PlanetCoaster", "Filter_Theme_Fairytale", "Filter_Theme_Resort", "Filter_PDLC_Toybox", "Filter_Theme_Toybox". 
function ModularScenery.Blueprint_Tags__Update__Tag(SceneryPart, Tag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Blueprint_Tags__Update__Tag", {SceneryPart, Tag}, 2)
end

--- Note: Autogenerated.
--- Inserter for table BrowserCategories.
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7. 
---@param Label string Common Values = "Browser_Cat_Shop_Drink", "Browser_Cat_Shop_Food", "Browser_Cat_Shop_Gift", "Browser_SubCat_Walls_Arches", "HUD_ShopMenu_Create". 
function ModularScenery.BrowserCategories__Insert(CategoryID, Label)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserCategories__Insert", {CategoryID, Label}, 2)
end

--- Note: Autogenerated.
--- Updates field "CategoryTag" in BrowserCategories. Common Values = nil, "Filter_BuildingProps_Spire", "Menu_Building_Arches_Archway", "Menu_Building_Decorations", "Menu_Building_Doors". 
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7.  (Lookup Key)
---@param CategoryTag string|nil Common Values = nil, "Filter_BuildingProps_Spire", "Menu_Building_Arches_Archway", "Menu_Building_Decorations", "Menu_Building_Doors". 
function ModularScenery.BrowserCategories__Update__CategoryTag(CategoryID, CategoryTag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserCategories__Update__CategoryTag", {CategoryID, CategoryTag}, 2)
end

--- Note: Autogenerated.
--- Updates field "Label" in BrowserCategories. Common Values = "Browser_Cat_Shop_Drink", "Browser_Cat_Shop_Food", "Browser_Cat_Shop_Gift", "Browser_SubCat_Walls_Arches", "HUD_ShopMenu_Create". 
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7.  (Lookup Key)
---@param Label string Common Values = "Browser_Cat_Shop_Drink", "Browser_Cat_Shop_Food", "Browser_Cat_Shop_Gift", "Browser_SubCat_Walls_Arches", "HUD_ShopMenu_Create". 
function ModularScenery.BrowserCategories__Update__Label(CategoryID, Label)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserCategories__Update__Label", {CategoryID, Label}, 2)
end

--- Note: Autogenerated.
--- Updates field "Icon" in BrowserCategories. Common Values = "HUDIconShops", "objectBrowserShopCounter", "categoryBrowserMenu_Create", "objectBrowserArches", "objectBrowserFramework". 
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7.  (Lookup Key)
---@param Icon string|nil Common Values = "HUDIconShops", "objectBrowserShopCounter", "categoryBrowserMenu_Create", "objectBrowserArches", "objectBrowserFramework". 
function ModularScenery.BrowserCategories__Update__Icon(CategoryID, Icon)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserCategories__Update__Icon", {CategoryID, Icon}, 2)
end

--- Note: Autogenerated.
--- Updates field "ParentID" in BrowserCategories. Common Values = 4, 3, 999, 1, 46. 
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7.  (Lookup Key)
---@param ParentID integer|nil Common Values = 4, 3, 999, 1, 46. 
function ModularScenery.BrowserCategories__Update__ParentID(CategoryID, ParentID)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserCategories__Update__ParentID", {CategoryID, ParentID}, 2)
end

--- Note: Autogenerated.
--- Updates field "Ordering" in BrowserCategories. Default = "1". Common Values = 2, 3, 1, 4, 5. 
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7.  (Lookup Key)
---@param Ordering integer Default = "1". Common Values = 2, 3, 1, 4, 5. 
function ModularScenery.BrowserCategories__Update__Ordering(CategoryID, Ordering)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserCategories__Update__Ordering", {CategoryID, Ordering}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioOpenSound" in BrowserCategories. Common Values = "Gui_MenuBarTab_SceneryPropsMisc", "Gui_MenuBarTab_SceneryPropsAll", "Gui_MenuBarTab_ShopsGift", "Gui_Select_Create_Scenery_Cameras", "Gui_MenuBarTab_BuildingsPathRoofsFlat". 
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7.  (Lookup Key)
---@param AudioOpenSound string|nil Common Values = "Gui_MenuBarTab_SceneryPropsMisc", "Gui_MenuBarTab_SceneryPropsAll", "Gui_MenuBarTab_ShopsGift", "Gui_Select_Create_Scenery_Cameras", "Gui_MenuBarTab_BuildingsPathRoofsFlat". 
function ModularScenery.BrowserCategories__Update__AudioOpenSound(CategoryID, AudioOpenSound)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserCategories__Update__AudioOpenSound", {CategoryID, AudioOpenSound}, 2)
end

--- Note: Autogenerated.
--- Updates field "UGCWorkshopTag" in BrowserCategories. Common Values = nil, "Arches", "Decorations", "Flat", "Signs and Ads". 
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7.  (Lookup Key)
---@param UGCWorkshopTag string|nil Common Values = nil, "Arches", "Decorations", "Flat", "Signs and Ads". 
function ModularScenery.BrowserCategories__Update__UGCWorkshopTag(CategoryID, UGCWorkshopTag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserCategories__Update__UGCWorkshopTag", {CategoryID, UGCWorkshopTag}, 2)
end

--- Note: Autogenerated.
--- Updates field "Category" in BrowserCategories. Common Values = nil, "Guests". 
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7.  (Lookup Key)
---@param Category string|nil Common Values = nil, "Guests". 
function ModularScenery.BrowserCategories__Update__Category(CategoryID, Category)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserCategories__Update__Category", {CategoryID, Category}, 2)
end

--- Note: Autogenerated.
--- Inserter for table BrowserFilters.
---@param FilterName string Common Values = "Belonging", "PlatformAttachment", "RestaurantTables", "SceneryBrush", "ShootableTarget". 
---@param Includes string Common Values = "ShootableTarget", "SurfaceScaling", "Billboard", "Firework", "SceneryPlatform". 
function ModularScenery.BrowserFilters__Insert(FilterName, Includes)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserFilters__Insert", {FilterName, Includes}, 2)
end

--- Note: Autogenerated.
--- Updates field "Includes" in BrowserFilters. Common Values = "ShootableTarget", "SurfaceScaling", "Billboard", "Firework", "SceneryPlatform". 
---@param FilterName string Common Values = "Belonging", "PlatformAttachment", "RestaurantTables", "SceneryBrush", "ShootableTarget".  (Lookup Key)
---@param Includes string Common Values = "ShootableTarget", "SurfaceScaling", "Billboard", "Firework", "SceneryPlatform". 
function ModularScenery.BrowserFilters__Update__Includes(FilterName, Includes)
    DatabaseUtils.ExecuteQuery("ModularScenery", "BrowserFilters__Update__Includes", {FilterName, Includes}, 2)
end

--- Note: Autogenerated.
--- Inserter for table ComplexTypes.
---@param Name string Common Values = "ChangingVillage", "Restaurant", "SouvenirShop". 
---@param EnumValue integer Common Values = 1, 2, 3. 
function ModularScenery.ComplexTypes__Insert(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ComplexTypes__Insert", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Updates field "EnumValue" in ComplexTypes. Common Values = 1, 2, 3. 
---@param Name string Common Values = "ChangingVillage", "Restaurant", "SouvenirShop".  (Lookup Key)
---@param EnumValue integer Common Values = 1, 2, 3. 
function ModularScenery.ComplexTypes__Update__EnumValue(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ComplexTypes__Update__EnumValue", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Inserter for table ContentPacks.
---@param Name string Common Values = "BaseGame", "Deluxe", "PDLC1", "PDLC2", "PDLC3". 
---@param EnumValue integer Common Values = 0, 1, 2, 4, 8. 
function ModularScenery.ContentPacks__Insert(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ContentPacks__Insert", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Updates field "EnumValue" in ContentPacks. Common Values = 0, 1, 2, 4, 8. 
---@param Name string Common Values = "BaseGame", "Deluxe", "PDLC1", "PDLC2", "PDLC3".  (Lookup Key)
---@param EnumValue integer Common Values = 0, 1, 2, 4, 8. 
function ModularScenery.ContentPacks__Update__EnumValue(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ContentPacks__Update__EnumValue", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Inserter for table DevTransitionList.
---@param SceneryPartName string|nil Common Values = "FX_Toybox_CartoonFire", "FX_Toybox_DustTrail", "FX_Toybox_LargeBeam", "FX_Toybox_PaintDrip", "FX_Toybox_PaintSplash". 
function ModularScenery.DevTransitionList__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "DevTransitionList__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
--- Inserter for table FacilityProps.
---@param SceneryPartName string Common Values = "DebugDryer", "Facility_ChangingRoom", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_GuestSpawner_Coach". 
function ModularScenery.FacilityProps__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "FacilityProps__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
--- Updates field "ShopInventoryName" in FacilityProps. Common Values = nil, "ChiefBeef", "CosmicCow", "Facility_HaystackDryer", "Facility_Staff_Building_Small". 
---@param SceneryPartName string Common Values = "DebugDryer", "Facility_ChangingRoom", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_GuestSpawner_Coach".  (Lookup Key)
---@param ShopInventoryName string|nil Common Values = nil, "ChiefBeef", "CosmicCow", "Facility_HaystackDryer", "Facility_Staff_Building_Small". 
function ModularScenery.FacilityProps__Update__ShopInventoryName(SceneryPartName, ShopInventoryName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "FacilityProps__Update__ShopInventoryName", {SceneryPartName, ShopInventoryName}, 2)
end

--- Note: Autogenerated.
--- Inserter for table FireworkEffects.
---@param SceneryPartName string Common Values = "DLC1_Firework_Chrysanthemum", "DLC1_Firework_ChrysanthemumLarge", "DLC1_Firework_Comet", "DLC1_Firework_CometMultiLaunch", "DLC1_Firework_Crossette". 
---@param Radius integer Common Values = 150, 200. 
---@param Magnitude integer Common Values = 8, 10, 12. 
---@param Duration number Common Values = 7.0, 5.0. 
function ModularScenery.FireworkEffects__Insert(SceneryPartName, Radius, Magnitude, Duration)
    DatabaseUtils.ExecuteQuery("ModularScenery", "FireworkEffects__Insert", {SceneryPartName, Radius, Magnitude, Duration}, 4)
end

--- Note: Autogenerated.
--- Updates field "Radius" in FireworkEffects. Common Values = 150, 200. 
---@param SceneryPartName string Common Values = "DLC1_Firework_Chrysanthemum", "DLC1_Firework_ChrysanthemumLarge", "DLC1_Firework_Comet", "DLC1_Firework_CometMultiLaunch", "DLC1_Firework_Crossette".  (Lookup Key)
---@param Radius integer Common Values = 150, 200. 
function ModularScenery.FireworkEffects__Update__Radius(SceneryPartName, Radius)
    DatabaseUtils.ExecuteQuery("ModularScenery", "FireworkEffects__Update__Radius", {SceneryPartName, Radius}, 2)
end

--- Note: Autogenerated.
--- Updates field "Magnitude" in FireworkEffects. Common Values = 8, 10, 12. 
---@param SceneryPartName string Common Values = "DLC1_Firework_Chrysanthemum", "DLC1_Firework_ChrysanthemumLarge", "DLC1_Firework_Comet", "DLC1_Firework_CometMultiLaunch", "DLC1_Firework_Crossette".  (Lookup Key)
---@param Magnitude integer Common Values = 8, 10, 12. 
function ModularScenery.FireworkEffects__Update__Magnitude(SceneryPartName, Magnitude)
    DatabaseUtils.ExecuteQuery("ModularScenery", "FireworkEffects__Update__Magnitude", {SceneryPartName, Magnitude}, 2)
end

--- Note: Autogenerated.
--- Updates field "Duration" in FireworkEffects. Common Values = 7.0, 5.0. 
---@param SceneryPartName string Common Values = "DLC1_Firework_Chrysanthemum", "DLC1_Firework_ChrysanthemumLarge", "DLC1_Firework_Comet", "DLC1_Firework_CometMultiLaunch", "DLC1_Firework_Crossette".  (Lookup Key)
---@param Duration number Common Values = 7.0, 5.0. 
function ModularScenery.FireworkEffects__Update__Duration(SceneryPartName, Duration)
    DatabaseUtils.ExecuteQuery("ModularScenery", "FireworkEffects__Update__Duration", {SceneryPartName, Duration}, 2)
end

--- Note: Autogenerated.
--- Inserter for table GridProps.
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim". 
---@param CellXSize number Common Values = 4.0, 2.0, 8.0, 1.0, 6.0. 
---@param CellYSize number Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
---@param CellZSize number Common Values = 4.0, 2.0, 8.0, 0.375, 0.5. 
---@param BoxXSize number Common Values = 4.0, 2.0, 0.667, 8.0, 0.5. 
---@param BoxYSize number Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
---@param BoxZSize number Common Values = 0.375, 4.0, 0.5, 2.0, 1.0. 
function ModularScenery.GridProps__Insert(SceneryPartName, CellXSize, CellYSize, CellZSize, BoxXSize, BoxYSize, BoxZSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "GridProps__Insert", {SceneryPartName, CellXSize, CellYSize, CellZSize, BoxXSize, BoxYSize, BoxZSize}, 7)
end

--- Note: Autogenerated.
--- Updates field "CellXSize" in GridProps. Common Values = 4.0, 2.0, 8.0, 1.0, 6.0. 
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim".  (Lookup Key)
---@param CellXSize number Common Values = 4.0, 2.0, 8.0, 1.0, 6.0. 
function ModularScenery.GridProps__Update__CellXSize(SceneryPartName, CellXSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "GridProps__Update__CellXSize", {SceneryPartName, CellXSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "CellYSize" in GridProps. Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim".  (Lookup Key)
---@param CellYSize number Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
function ModularScenery.GridProps__Update__CellYSize(SceneryPartName, CellYSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "GridProps__Update__CellYSize", {SceneryPartName, CellYSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "CellZSize" in GridProps. Common Values = 4.0, 2.0, 8.0, 0.375, 0.5. 
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim".  (Lookup Key)
---@param CellZSize number Common Values = 4.0, 2.0, 8.0, 0.375, 0.5. 
function ModularScenery.GridProps__Update__CellZSize(SceneryPartName, CellZSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "GridProps__Update__CellZSize", {SceneryPartName, CellZSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "BoxXSize" in GridProps. Common Values = 4.0, 2.0, 0.667, 8.0, 0.5. 
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim".  (Lookup Key)
---@param BoxXSize number Common Values = 4.0, 2.0, 0.667, 8.0, 0.5. 
function ModularScenery.GridProps__Update__BoxXSize(SceneryPartName, BoxXSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "GridProps__Update__BoxXSize", {SceneryPartName, BoxXSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "BoxYSize" in GridProps. Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim".  (Lookup Key)
---@param BoxYSize number Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
function ModularScenery.GridProps__Update__BoxYSize(SceneryPartName, BoxYSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "GridProps__Update__BoxYSize", {SceneryPartName, BoxYSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "BoxZSize" in GridProps. Common Values = 0.375, 4.0, 0.5, 2.0, 1.0. 
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim".  (Lookup Key)
---@param BoxZSize number Common Values = 0.375, 4.0, 0.5, 2.0, 1.0. 
function ModularScenery.GridProps__Update__BoxZSize(SceneryPartName, BoxZSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "GridProps__Update__BoxZSize", {SceneryPartName, BoxZSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "AlignmentStyle" in GridProps. Default = "Middle". Common Values = "EdgesNESW", "Middle", "Corners", "EdgesNESW_ZCentred". 
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim".  (Lookup Key)
---@param AlignmentStyle string Default = "Middle". Common Values = "EdgesNESW", "Middle", "Corners", "EdgesNESW_ZCentred". 
function ModularScenery.GridProps__Update__AlignmentStyle(SceneryPartName, AlignmentStyle)
    DatabaseUtils.ExecuteQuery("ModularScenery", "GridProps__Update__AlignmentStyle", {SceneryPartName, AlignmentStyle}, 2)
end

--- Note: Autogenerated.
--- Inserter for table LocalGridAlignmentStyle.
---@param Name string Common Values = "Corners", "EdgesNESW", "EdgesNESW_ZCentred", "Middle", "NoAlign". 
---@param EnumValue integer Common Values = 0, 1, 2, 3, 4. 
function ModularScenery.LocalGridAlignmentStyle__Insert(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "LocalGridAlignmentStyle__Insert", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Updates field "EnumValue" in LocalGridAlignmentStyle. Common Values = 0, 1, 2, 3, 4. 
---@param Name string Common Values = "Corners", "EdgesNESW", "EdgesNESW_ZCentred", "Middle", "NoAlign".  (Lookup Key)
---@param EnumValue integer Common Values = 0, 1, 2, 3, 4. 
function ModularScenery.LocalGridAlignmentStyle__Update__EnumValue(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "LocalGridAlignmentStyle__Update__EnumValue", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Inserter for table Metadata_Tags.
---@param SceneryPart string Common Values = "VI_Bellows_01", "AQ_Roof_Corrugated_Slope_Eave_Corner_4m", "AQ_Wall_Bevelled_Merge_1m", "AQ_Wall_Bevelled_Merge_2m", "AQ_Wall_Bevelled_Merge_4m". 
---@param Tag string Common Values = "Filter_PDLC_None", "Filter_GridProperty_OffGrid", "Filter_Property_FlexiColour", "Filter_WallSet_Basic", "Filter_BaseMaterial_Metal". 
function ModularScenery.Metadata_Tags__Insert(SceneryPart, Tag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Metadata_Tags__Insert", {SceneryPart, Tag}, 2)
end

--- Note: Autogenerated.
--- Updates field "Tag" in Metadata_Tags. Common Values = "Filter_PDLC_None", "Filter_GridProperty_OffGrid", "Filter_Property_FlexiColour", "Filter_WallSet_Basic", "Filter_BaseMaterial_Metal". 
---@param SceneryPart string Common Values = "VI_Bellows_01", "AQ_Roof_Corrugated_Slope_Eave_Corner_4m", "AQ_Wall_Bevelled_Merge_1m", "AQ_Wall_Bevelled_Merge_2m", "AQ_Wall_Bevelled_Merge_4m".  (Lookup Key)
---@param Tag string Common Values = "Filter_PDLC_None", "Filter_GridProperty_OffGrid", "Filter_Property_FlexiColour", "Filter_WallSet_Basic", "Filter_BaseMaterial_Metal". 
function ModularScenery.Metadata_Tags__Update__Tag(SceneryPart, Tag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Metadata_Tags__Update__Tag", {SceneryPart, Tag}, 2)
end

--- Note: Autogenerated.
--- Inserter for table ModularSceneryParts.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
---@param DataPrefabName string Common Values = "SurfaceScaling", "OnGrid", "TriggerableScalableScenery", "SignScaling", "TriggerableScenery". 
---@param ContentPack string Common Values = "BaseGame", "PDLC3", "PDLC2". 
function ModularScenery.ModularSceneryParts__Insert(SceneryPartName, DataPrefabName, ContentPack)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ModularSceneryParts__Insert", {SceneryPartName, DataPrefabName, ContentPack}, 3)
end

--- Note: Autogenerated.
--- Updates field "PrefabName" in ModularSceneryParts. Common Values = nil, "PlaceholderActualParkEntrance", "RR_ParkEntrance", "SF_Outpost_Soldier_Animatronic_Green", "SF_Outpost_Soldier_Animatronic_Green_Computer". 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param PrefabName string|nil Common Values = nil, "PlaceholderActualParkEntrance", "RR_ParkEntrance", "SF_Outpost_Soldier_Animatronic_Green", "SF_Outpost_Soldier_Animatronic_Green_Computer". 
function ModularScenery.ModularSceneryParts__Update__PrefabName(SceneryPartName, PrefabName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ModularSceneryParts__Update__PrefabName", {SceneryPartName, PrefabName}, 2)
end

--- Note: Autogenerated.
--- Updates field "DataPrefabName" in ModularSceneryParts. Common Values = "SurfaceScaling", "OnGrid", "TriggerableScalableScenery", "SignScaling", "TriggerableScenery". 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param DataPrefabName string Common Values = "SurfaceScaling", "OnGrid", "TriggerableScalableScenery", "SignScaling", "TriggerableScenery". 
function ModularScenery.ModularSceneryParts__Update__DataPrefabName(SceneryPartName, DataPrefabName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ModularSceneryParts__Update__DataPrefabName", {SceneryPartName, DataPrefabName}, 2)
end

--- Note: Autogenerated.
--- Updates field "ContentPack" in ModularSceneryParts. Common Values = "BaseGame", "PDLC3", "PDLC2". 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param ContentPack string Common Values = "BaseGame", "PDLC3", "PDLC2". 
function ModularScenery.ModularSceneryParts__Update__ContentPack(SceneryPartName, ContentPack)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ModularSceneryParts__Update__ContentPack", {SceneryPartName, ContentPack}, 2)
end

--- Note: Autogenerated.
--- Updates field "UGCID" in ModularSceneryParts. Default = "NULL". Common Values = nil, "". 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param UGCID string|nil Default = "NULL". Common Values = nil, "". 
function ModularScenery.ModularSceneryParts__Update__UGCID(SceneryPartName, UGCID)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ModularSceneryParts__Update__UGCID", {SceneryPartName, UGCID}, 2)
end

--- Note: Autogenerated.
--- Updates field "BoxXSize" in ModularSceneryParts. Common Values = nil, 4.0, 2.0, 1.0, 400.0. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param BoxXSize number|nil Common Values = nil, 4.0, 2.0, 1.0, 400.0. 
function ModularScenery.ModularSceneryParts__Update__BoxXSize(SceneryPartName, BoxXSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ModularSceneryParts__Update__BoxXSize", {SceneryPartName, BoxXSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "BoxYSize" in ModularSceneryParts. Common Values = nil, 4.0, 2.0, 0.0, 1.0. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param BoxYSize number|nil Common Values = nil, 4.0, 2.0, 0.0, 1.0. 
function ModularScenery.ModularSceneryParts__Update__BoxYSize(SceneryPartName, BoxYSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ModularSceneryParts__Update__BoxYSize", {SceneryPartName, BoxYSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "BoxZSize" in ModularSceneryParts. Common Values = nil, 4.0, 0.375, 2.0, 0.5. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param BoxZSize number|nil Common Values = nil, 4.0, 0.375, 2.0, 0.5. 
function ModularScenery.ModularSceneryParts__Update__BoxZSize(SceneryPartName, BoxZSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ModularSceneryParts__Update__BoxZSize", {SceneryPartName, BoxZSize}, 2)
end

--- Note: Autogenerated.
--- Inserter for table PartComplexMembers.
---@param SceneryPartName string Common Values = "Facility_ChangingRoom", "Facility_Restaurant_Kitchen", "Facility_SouvenirShop_Counter". 
function ModularScenery.PartComplexMembers__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PartComplexMembers__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
--- Updates field "MustBelongToComplexOfType" in PartComplexMembers. Common Values = "ChangingVillage", "Restaurant", "SouvenirShop". 
---@param SceneryPartName string Common Values = "Facility_ChangingRoom", "Facility_Restaurant_Kitchen", "Facility_SouvenirShop_Counter".  (Lookup Key)
---@param MustBelongToComplexOfType string|nil Common Values = "ChangingVillage", "Restaurant", "SouvenirShop". 
function ModularScenery.PartComplexMembers__Update__MustBelongToComplexOfType(SceneryPartName, MustBelongToComplexOfType)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PartComplexMembers__Update__MustBelongToComplexOfType", {SceneryPartName, MustBelongToComplexOfType}, 2)
end

--- Note: Autogenerated.
--- Inserter for table PartControlPoints.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
function ModularScenery.PartControlPoints__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PartControlPoints__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
--- Updates field "ControlPointX" in PartControlPoints. Default = "0". Common Values = 0.0, -2.842170943040401e-16, 0.6485724901865763, 6.0. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param ControlPointX number Default = "0". Common Values = 0.0, -2.842170943040401e-16, 0.6485724901865763, 6.0. 
function ModularScenery.PartControlPoints__Update__ControlPointX(SceneryPartName, ControlPointX)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PartControlPoints__Update__ControlPointX", {SceneryPartName, ControlPointX}, 2)
end

--- Note: Autogenerated.
--- Updates field "ControlPointY" in PartControlPoints. Default = "0". Common Values = 0.0, -0.25, -1.0, -2.0, -0.662266502. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param ControlPointY number Default = "0". Common Values = 0.0, -0.25, -1.0, -2.0, -0.662266502. 
function ModularScenery.PartControlPoints__Update__ControlPointY(SceneryPartName, ControlPointY)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PartControlPoints__Update__ControlPointY", {SceneryPartName, ControlPointY}, 2)
end

--- Note: Autogenerated.
--- Updates field "ControlPointZ" in PartControlPoints. Default = "0". Common Values = 0.0, -2.0, -1.0, -0.5, -2.8. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param ControlPointZ number Default = "0". Common Values = 0.0, -2.0, -1.0, -0.5, -2.8. 
function ModularScenery.PartControlPoints__Update__ControlPointZ(SceneryPartName, ControlPointZ)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PartControlPoints__Update__ControlPointZ", {SceneryPartName, ControlPointZ}, 2)
end

--- Note: Autogenerated.
--- Inserter for table PartCustomFilterIDs.
---@param SceneryPartName string Common Values = "AQ_PicnicBench_01", "AQ_PicnicBench_02", "FT_PicnicBench_01", "FT_PicnicBench_02", "Facility_SouvenirShop_Balloons_Display". 
---@param CustomFilterID string Common Values = "CustomFilter_RestaurantTables", "CustomFilter_SouvenirShop". 
function ModularScenery.PartCustomFilterIDs__Insert(SceneryPartName, CustomFilterID)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PartCustomFilterIDs__Insert", {SceneryPartName, CustomFilterID}, 2)
end

--- Note: Autogenerated.
--- Updates field "CustomFilterID" in PartCustomFilterIDs. Common Values = "CustomFilter_RestaurantTables", "CustomFilter_SouvenirShop". 
---@param SceneryPartName string Common Values = "AQ_PicnicBench_01", "AQ_PicnicBench_02", "FT_PicnicBench_01", "FT_PicnicBench_02", "Facility_SouvenirShop_Balloons_Display".  (Lookup Key)
---@param CustomFilterID string Common Values = "CustomFilter_RestaurantTables", "CustomFilter_SouvenirShop". 
function ModularScenery.PartCustomFilterIDs__Update__CustomFilterID(SceneryPartName, CustomFilterID)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PartCustomFilterIDs__Update__CustomFilterID", {SceneryPartName, CustomFilterID}, 2)
end

--- Note: Autogenerated.
--- Inserter for table PartDataPrefabs.
---@param PrefabName string Common Values = "Billboard", "BuildingGroup", "ChangingRoom", "Facility", "FacilityComplex". 
function ModularScenery.PartDataPrefabs__Insert(PrefabName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PartDataPrefabs__Insert", {PrefabName}, 1)
end

--- Note: Autogenerated.
--- Inserter for table PathExtraProps.
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01". 
---@param BoxXSize number Common Values = 2.455, 0.593, 0.77, 2.0, 0.75. 
---@param BoxYSize number Common Values = 4.0, 0.881, 0.2, 1.866, 2.0. 
---@param BoxZSize number Common Values = 2.0, 0.652, 0.2, 0.6, 1.0. 
---@param SnapType string Common Values = "Path", "Pool", "Pool_WaveMachine", "Path_LifeguardPost", "Pool_WaterPump". 
function ModularScenery.PathExtraProps__Insert(SceneryPartName, BoxXSize, BoxYSize, BoxZSize, SnapType)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PathExtraProps__Insert", {SceneryPartName, BoxXSize, BoxYSize, BoxZSize, SnapType}, 5)
end

--- Note: Autogenerated.
--- Updates field "BoxXSize" in PathExtraProps. Common Values = 2.455, 0.593, 0.77, 2.0, 0.75. 
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01".  (Lookup Key)
---@param BoxXSize number Common Values = 2.455, 0.593, 0.77, 2.0, 0.75. 
function ModularScenery.PathExtraProps__Update__BoxXSize(SceneryPartName, BoxXSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PathExtraProps__Update__BoxXSize", {SceneryPartName, BoxXSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "BoxYSize" in PathExtraProps. Common Values = 4.0, 0.881, 0.2, 1.866, 2.0. 
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01".  (Lookup Key)
---@param BoxYSize number Common Values = 4.0, 0.881, 0.2, 1.866, 2.0. 
function ModularScenery.PathExtraProps__Update__BoxYSize(SceneryPartName, BoxYSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PathExtraProps__Update__BoxYSize", {SceneryPartName, BoxYSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "BoxZSize" in PathExtraProps. Common Values = 2.0, 0.652, 0.2, 0.6, 1.0. 
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01".  (Lookup Key)
---@param BoxZSize number Common Values = 2.0, 0.652, 0.2, 0.6, 1.0. 
function ModularScenery.PathExtraProps__Update__BoxZSize(SceneryPartName, BoxZSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PathExtraProps__Update__BoxZSize", {SceneryPartName, BoxZSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "SnapType" in PathExtraProps. Common Values = "Path", "Pool", "Pool_WaveMachine", "Path_LifeguardPost", "Pool_WaterPump". 
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01".  (Lookup Key)
---@param SnapType string Common Values = "Path", "Pool", "Pool_WaveMachine", "Path_LifeguardPost", "Pool_WaterPump". 
function ModularScenery.PathExtraProps__Update__SnapType(SceneryPartName, SnapType)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PathExtraProps__Update__SnapType", {SceneryPartName, SnapType}, 2)
end

--- Note: Autogenerated.
--- Inserter for table PathExtraSnapType.
---@param SnapTypeName string Common Values = "Path", "Path_LifeguardPost", "Pool", "Pool_WaterPump", "Pool_WaveMachine". 
---@param SnapTypeValue integer Common Values = 1, 2, 3, 4, 5. 
function ModularScenery.PathExtraSnapType__Insert(SnapTypeName, SnapTypeValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PathExtraSnapType__Insert", {SnapTypeName, SnapTypeValue}, 2)
end

--- Note: Autogenerated.
--- Updates field "SnapTypeValue" in PathExtraSnapType. Common Values = 1, 2, 3, 4, 5. 
---@param SnapTypeName string Common Values = "Path", "Path_LifeguardPost", "Pool", "Pool_WaterPump", "Pool_WaveMachine".  (Lookup Key)
---@param SnapTypeValue integer Common Values = 1, 2, 3, 4, 5. 
function ModularScenery.PathExtraSnapType__Update__SnapTypeValue(SnapTypeName, SnapTypeValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PathExtraSnapType__Update__SnapTypeValue", {SnapTypeName, SnapTypeValue}, 2)
end

--- Note: Autogenerated.
--- Inserter for table PathProps.
---@param SceneryPartName string Common Values = "DebugDryer", "Facility_ChangingRoom", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_GuestSpawner_Coach". 
---@param JoinPartResourceName string Common Values = "FacilityJoin", "FacilityJoin_Small_NoControlPanel", "ParkEntranceJoinPart", "FacilityJoin_Large_LeftEntrance", "FacilityJoin_Medium". 
function ModularScenery.PathProps__Insert(SceneryPartName, JoinPartResourceName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PathProps__Insert", {SceneryPartName, JoinPartResourceName}, 2)
end

--- Note: Autogenerated.
--- Updates field "JoinPartResourceName" in PathProps. Common Values = "FacilityJoin", "FacilityJoin_Small_NoControlPanel", "ParkEntranceJoinPart", "FacilityJoin_Large_LeftEntrance", "FacilityJoin_Medium". 
---@param SceneryPartName string Common Values = "DebugDryer", "Facility_ChangingRoom", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_GuestSpawner_Coach".  (Lookup Key)
---@param JoinPartResourceName string Common Values = "FacilityJoin", "FacilityJoin_Small_NoControlPanel", "ParkEntranceJoinPart", "FacilityJoin_Large_LeftEntrance", "FacilityJoin_Medium". 
function ModularScenery.PathProps__Update__JoinPartResourceName(SceneryPartName, JoinPartResourceName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "PathProps__Update__JoinPartResourceName", {SceneryPartName, JoinPartResourceName}, 2)
end

--- Note: Autogenerated.
--- Inserter for table SceneryScaling.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_CargoLift", "AQ_CargoLift_FootBase", "AQ_CargoLift_FootWall", "AQ_Coral_Anemone_01". 
---@param MinSize number Common Values = 0.5, 0.25, 0.2, 0.05, 0.3. 
---@param MaxSize number Common Values = 3.0, 5.0, 2.0, 1.4, 2.5. 
function ModularScenery.SceneryScaling__Insert(SceneryPartName, MinSize, MaxSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "SceneryScaling__Insert", {SceneryPartName, MinSize, MaxSize}, 3)
end

--- Note: Autogenerated.
--- Updates field "MinSize" in SceneryScaling. Common Values = 0.5, 0.25, 0.2, 0.05, 0.3. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_CargoLift", "AQ_CargoLift_FootBase", "AQ_CargoLift_FootWall", "AQ_Coral_Anemone_01".  (Lookup Key)
---@param MinSize number Common Values = 0.5, 0.25, 0.2, 0.05, 0.3. 
function ModularScenery.SceneryScaling__Update__MinSize(SceneryPartName, MinSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "SceneryScaling__Update__MinSize", {SceneryPartName, MinSize}, 2)
end

--- Note: Autogenerated.
--- Updates field "MaxSize" in SceneryScaling. Common Values = 3.0, 5.0, 2.0, 1.4, 2.5. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_CargoLift", "AQ_CargoLift_FootBase", "AQ_CargoLift_FootWall", "AQ_Coral_Anemone_01".  (Lookup Key)
---@param MaxSize number Common Values = 3.0, 5.0, 2.0, 1.4, 2.5. 
function ModularScenery.SceneryScaling__Update__MaxSize(SceneryPartName, MaxSize)
    DatabaseUtils.ExecuteQuery("ModularScenery", "SceneryScaling__Update__MaxSize", {SceneryPartName, MaxSize}, 2)
end

--- Note: Autogenerated.
--- Inserter for table Simulation.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
---@param BuildCost integer Common Values = 200, 400, 1800, 350, 1400. 
function ModularScenery.Simulation__Insert(SceneryPartName, BuildCost)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Simulation__Insert", {SceneryPartName, BuildCost}, 2)
end

--- Note: Autogenerated.
--- Updates field "BuildCost" in Simulation. Common Values = 200, 400, 1800, 350, 1400. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param BuildCost integer Common Values = 200, 400, 1800, 350, 1400. 
function ModularScenery.Simulation__Update__BuildCost(SceneryPartName, BuildCost)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Simulation__Update__BuildCost", {SceneryPartName, BuildCost}, 2)
end

--- Note: Autogenerated.
--- Updates field "HourlyRunningCost" in Simulation. Common Values = 0. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param HourlyRunningCost integer|nil Common Values = 0. 
function ModularScenery.Simulation__Update__HourlyRunningCost(SceneryPartName, HourlyRunningCost)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Simulation__Update__HourlyRunningCost", {SceneryPartName, HourlyRunningCost}, 2)
end

--- Note: Autogenerated.
--- Updates field "ResearchPack" in Simulation. Common Values = nil, 1000, 1001, 2300, 2301. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param ResearchPack integer|nil Common Values = nil, 1000, 1001, 2300, 2301. 
function ModularScenery.Simulation__Update__ResearchPack(SceneryPartName, ResearchPack)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Simulation__Update__ResearchPack", {SceneryPartName, ResearchPack}, 2)
end

--- Note: Autogenerated.
--- Updates field "RequiresUnlockInSandbox" in Simulation. Common Values = 0, 1. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param RequiresUnlockInSandbox boolean|nil Common Values = 0, 1. 
function ModularScenery.Simulation__Update__RequiresUnlockInSandbox(SceneryPartName, RequiresUnlockInSandbox)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Simulation__Update__RequiresUnlockInSandbox", {SceneryPartName, RequiresUnlockInSandbox}, 2)
end

--- Note: Autogenerated.
--- Inserter for table SnapEdgePartData.
---@param SceneryPartName string Common Values = "SnapEdge_12m", "SnapEdge_16m", "SnapEdge_1m", "SnapEdge_2m", "SnapEdge_4m". 
---@param Size integer Common Values = 1, 2, 4, 8, 12. 
function ModularScenery.SnapEdgePartData__Insert(SceneryPartName, Size)
    DatabaseUtils.ExecuteQuery("ModularScenery", "SnapEdgePartData__Insert", {SceneryPartName, Size}, 2)
end

--- Note: Autogenerated.
--- Updates field "Size" in SnapEdgePartData. Common Values = 1, 2, 4, 8, 12. 
---@param SceneryPartName string Common Values = "SnapEdge_12m", "SnapEdge_16m", "SnapEdge_1m", "SnapEdge_2m", "SnapEdge_4m".  (Lookup Key)
---@param Size integer Common Values = 1, 2, 4, 8, 12. 
function ModularScenery.SnapEdgePartData__Update__Size(SceneryPartName, Size)
    DatabaseUtils.ExecuteQuery("ModularScenery", "SnapEdgePartData__Update__Size", {SceneryPartName, Size}, 2)
end

--- Note: Autogenerated.
--- Inserter for table TagGroups.
---@param TagGroup string Common Values = "FilterGroup_BuildingPieces_WallSet", "FilterGroup_All_BaseMaterial", "FilterGroup_BrandedPieces_Brand", "FilterGroup_Scenery_Group", "FilterGroup_BuildingPieces_Type". 
---@param Tag string Common Values = "Filter_BaseMaterial_Bamboo", "Filter_BaseMaterial_Biscuit", "Filter_BaseMaterial_Brick", "Filter_BaseMaterial_Card", "Filter_BaseMaterial_Ceramic". 
function ModularScenery.TagGroups__Insert(TagGroup, Tag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagGroups__Insert", {TagGroup, Tag}, 2)
end

--- Note: Autogenerated.
--- Updates field "Tag" in TagGroups. Common Values = "Filter_BaseMaterial_Bamboo", "Filter_BaseMaterial_Biscuit", "Filter_BaseMaterial_Brick", "Filter_BaseMaterial_Card", "Filter_BaseMaterial_Ceramic". 
---@param TagGroup string Common Values = "FilterGroup_BuildingPieces_WallSet", "FilterGroup_All_BaseMaterial", "FilterGroup_BrandedPieces_Brand", "FilterGroup_Scenery_Group", "FilterGroup_BuildingPieces_Type".  (Lookup Key)
---@param Tag string Common Values = "Filter_BaseMaterial_Bamboo", "Filter_BaseMaterial_Biscuit", "Filter_BaseMaterial_Brick", "Filter_BaseMaterial_Card", "Filter_BaseMaterial_Ceramic". 
function ModularScenery.TagGroups__Update__Tag(TagGroup, Tag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagGroups__Update__Tag", {TagGroup, Tag}, 2)
end

--- Note: Autogenerated.
--- Updates field "Ordering" in TagGroups. Default = "0". Common Values = 5, 1, 2, 3, 4. 
---@param TagGroup string Common Values = "FilterGroup_BuildingPieces_WallSet", "FilterGroup_All_BaseMaterial", "FilterGroup_BrandedPieces_Brand", "FilterGroup_Scenery_Group", "FilterGroup_BuildingPieces_Type".  (Lookup Key)
---@param Ordering integer Default = "0". Common Values = 5, 1, 2, 3, 4. 
function ModularScenery.TagGroups__Update__Ordering(TagGroup, Ordering)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagGroups__Update__Ordering", {TagGroup, Ordering}, 2)
end

--- Note: Autogenerated.
--- Inserter for table TagGroupsDefinition.
---@param Name string Common Values = "FilterGroup_All_BaseMaterial", "FilterGroup_All_ContentPack", "FilterGroup_All_GridProperty", "FilterGroup_All_Theme", "FilterGroup_BrandedPieces_Brand". 
---@param TextSymbol string Common Values = "TagGroup_BaseMaterial", "TagGroup_Brand", "TagGroup_Grid", "TagGroup_Nature", "TagGroup_PDLC". 
function ModularScenery.TagGroupsDefinition__Insert(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagGroupsDefinition__Insert", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
--- Updates field "TextSymbol" in TagGroupsDefinition. Common Values = "TagGroup_BaseMaterial", "TagGroup_Brand", "TagGroup_Grid", "TagGroup_Nature", "TagGroup_PDLC". 
---@param Name string Common Values = "FilterGroup_All_BaseMaterial", "FilterGroup_All_ContentPack", "FilterGroup_All_GridProperty", "FilterGroup_All_Theme", "FilterGroup_BrandedPieces_Brand".  (Lookup Key)
---@param TextSymbol string Common Values = "TagGroup_BaseMaterial", "TagGroup_Brand", "TagGroup_Grid", "TagGroup_Nature", "TagGroup_PDLC". 
function ModularScenery.TagGroupsDefinition__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagGroupsDefinition__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
--- Updates field "Ordering" in TagGroupsDefinition. Default = "0". Common Values = 1, 6, 9, 10, 12. 
---@param Name string Common Values = "FilterGroup_All_BaseMaterial", "FilterGroup_All_ContentPack", "FilterGroup_All_GridProperty", "FilterGroup_All_Theme", "FilterGroup_BrandedPieces_Brand".  (Lookup Key)
---@param Ordering integer Default = "0". Common Values = 1, 6, 9, 10, 12. 
function ModularScenery.TagGroupsDefinition__Update__Ordering(Name, Ordering)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagGroupsDefinition__Update__Ordering", {Name, Ordering}, 2)
end

--- Note: Autogenerated.
--- Inserter for table TagGroupsToBrowserTabs.
---@param TabGroup string Common Values = "FilterGroup_All_ContentPack", "FilterGroup_BrandedPieces_Brand", "FilterGroup_All_BaseMaterial", "FilterGroup_All_Theme", "FilterGroup_BuildingPieces_Height". 
---@param BrowserTab string Common Values = "scenery", "buildings", "shops". 
function ModularScenery.TagGroupsToBrowserTabs__Insert(TabGroup, BrowserTab)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagGroupsToBrowserTabs__Insert", {TabGroup, BrowserTab}, 2)
end

--- Note: Autogenerated.
--- Updates field "BrowserTab" in TagGroupsToBrowserTabs. Common Values = "scenery", "buildings", "shops". 
---@param TabGroup string Common Values = "FilterGroup_All_ContentPack", "FilterGroup_BrandedPieces_Brand", "FilterGroup_All_BaseMaterial", "FilterGroup_All_Theme", "FilterGroup_BuildingPieces_Height".  (Lookup Key)
---@param BrowserTab string Common Values = "scenery", "buildings", "shops". 
function ModularScenery.TagGroupsToBrowserTabs__Update__BrowserTab(TabGroup, BrowserTab)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagGroupsToBrowserTabs__Update__BrowserTab", {TabGroup, BrowserTab}, 2)
end

--- Note: Autogenerated.
--- Updates field "Ordering" in TagGroupsToBrowserTabs. Default = "0". Common Values = 1, 2, 4, 7, 8. 
---@param TabGroup string Common Values = "FilterGroup_All_ContentPack", "FilterGroup_BrandedPieces_Brand", "FilterGroup_All_BaseMaterial", "FilterGroup_All_Theme", "FilterGroup_BuildingPieces_Height".  (Lookup Key)
---@param Ordering integer Default = "0". Common Values = 1, 2, 4, 7, 8. 
function ModularScenery.TagGroupsToBrowserTabs__Update__Ordering(TabGroup, Ordering)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagGroupsToBrowserTabs__Update__Ordering", {TabGroup, Ordering}, 2)
end

--- Note: Autogenerated.
--- Inserter for table TagSet.
---@param Tag string Common Values = "Code_SceneryType_BodyDryer", "Code_SceneryType_ChangingRoom", "Code_SceneryType_DivingBoard", "Code_SceneryType_GuestServices", "Code_SceneryType_LifeguardPoint". 
---@param TextSymbol string Common Values = "Browser_Cat_Shop_Power_Utility", "Browser_Cat_Shop_Water_Utility", "Tag_Menu_PoolExtra_Accessories", "Tag_Dev", "Browser_Cat_Shop_Info". 
function ModularScenery.TagSet__Insert(Tag, TextSymbol)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagSet__Insert", {Tag, TextSymbol}, 2)
end

--- Note: Autogenerated.
--- Updates field "TextSymbol" in TagSet. Common Values = "Browser_Cat_Shop_Power_Utility", "Browser_Cat_Shop_Water_Utility", "Tag_Menu_PoolExtra_Accessories", "Tag_Dev", "Browser_Cat_Shop_Info". 
---@param Tag string Common Values = "Code_SceneryType_BodyDryer", "Code_SceneryType_ChangingRoom", "Code_SceneryType_DivingBoard", "Code_SceneryType_GuestServices", "Code_SceneryType_LifeguardPoint".  (Lookup Key)
---@param TextSymbol string Common Values = "Browser_Cat_Shop_Power_Utility", "Browser_Cat_Shop_Water_Utility", "Tag_Menu_PoolExtra_Accessories", "Tag_Dev", "Browser_Cat_Shop_Info". 
function ModularScenery.TagSet__Update__TextSymbol(Tag, TextSymbol)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagSet__Update__TextSymbol", {Tag, TextSymbol}, 2)
end

--- Note: Autogenerated.
--- Updates field "IconPath" in TagSet. Common Values = nil. 
---@param Tag string Common Values = "Code_SceneryType_BodyDryer", "Code_SceneryType_ChangingRoom", "Code_SceneryType_DivingBoard", "Code_SceneryType_GuestServices", "Code_SceneryType_LifeguardPoint".  (Lookup Key)
---@param IconPath string|nil Common Values = nil. 
function ModularScenery.TagSet__Update__IconPath(Tag, IconPath)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TagSet__Update__IconPath", {Tag, IconPath}, 2)
end

--- Note: Autogenerated.
--- Inserter for table ThemeNames.
---@param ThemeName string Common Values = "Theme_Aquatic", "Theme_Fairytale", "Theme_Festive", "Theme_Mythology", "Theme_Nature". 
---@param Tag string Common Values = "Filter_Theme_Aquatic", "Filter_Theme_Fairytale", "Filter_Theme_Festive", "Filter_Theme_Mythology", "Filter_Theme_Nature". 
---@param LocTag string Common Values = "Tag_Theme_Fairytale", "Tag_Theme_Festive", "Tag_Theme_Pirate", "Tag_Theme_SciFi", "Tag_Theme_Sorcery". 
function ModularScenery.ThemeNames__Insert(ThemeName, Tag, LocTag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ThemeNames__Insert", {ThemeName, Tag, LocTag}, 3)
end

--- Note: Autogenerated.
--- Updates field "Tag" in ThemeNames. Common Values = "Filter_Theme_Aquatic", "Filter_Theme_Fairytale", "Filter_Theme_Festive", "Filter_Theme_Mythology", "Filter_Theme_Nature". 
---@param ThemeName string Common Values = "Theme_Aquatic", "Theme_Fairytale", "Theme_Festive", "Theme_Mythology", "Theme_Nature".  (Lookup Key)
---@param Tag string Common Values = "Filter_Theme_Aquatic", "Filter_Theme_Fairytale", "Filter_Theme_Festive", "Filter_Theme_Mythology", "Filter_Theme_Nature". 
function ModularScenery.ThemeNames__Update__Tag(ThemeName, Tag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ThemeNames__Update__Tag", {ThemeName, Tag}, 2)
end

--- Note: Autogenerated.
--- Updates field "LocTag" in ThemeNames. Common Values = "Tag_Theme_Fairytale", "Tag_Theme_Festive", "Tag_Theme_Pirate", "Tag_Theme_SciFi", "Tag_Theme_Sorcery". 
---@param ThemeName string Common Values = "Theme_Aquatic", "Theme_Fairytale", "Theme_Festive", "Theme_Mythology", "Theme_Nature".  (Lookup Key)
---@param LocTag string Common Values = "Tag_Theme_Fairytale", "Tag_Theme_Festive", "Tag_Theme_Pirate", "Tag_Theme_SciFi", "Tag_Theme_Sorcery". 
function ModularScenery.ThemeNames__Update__LocTag(ThemeName, LocTag)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ThemeNames__Update__LocTag", {ThemeName, LocTag}, 2)
end

--- Note: Autogenerated.
--- Updates field "ContentPack" in ThemeNames. Common Values = "BaseGame", "PDLC2", "PDLC3". 
---@param ThemeName string Common Values = "Theme_Aquatic", "Theme_Fairytale", "Theme_Festive", "Theme_Mythology", "Theme_Nature".  (Lookup Key)
---@param ContentPack string|nil Common Values = "BaseGame", "PDLC2", "PDLC3". 
function ModularScenery.ThemeNames__Update__ContentPack(ThemeName, ContentPack)
    DatabaseUtils.ExecuteQuery("ModularScenery", "ThemeNames__Update__ContentPack", {ThemeName, ContentPack}, 2)
end

--- Note: Autogenerated.
--- Inserter for table Theming.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
function ModularScenery.Theming__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Theming__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
--- Updates field "Weight" in Theming. Default = "0". Common Values = 80, 110, 190, 120, 150. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param Weight integer Default = "0". Common Values = 80, 110, 190, 120, 150. 
function ModularScenery.Theming__Update__Weight(SceneryPartName, Weight)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Theming__Update__Weight", {SceneryPartName, Weight}, 2)
end

--- Note: Autogenerated.
--- Updates field "Radius" in Theming. Default = "0". Common Values = 9, 11, 8, 10, 0. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param Radius integer Default = "0". Common Values = 9, 11, 8, 10, 0. 
function ModularScenery.Theming__Update__Radius(SceneryPartName, Radius)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Theming__Update__Radius", {SceneryPartName, Radius}, 2)
end

--- Note: Autogenerated.
--- Updates field "FalloffRadius" in Theming. Default = "0". Common Values = 16, 19, 17, 18, 20. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param FalloffRadius integer Default = "0". Common Values = 16, 19, 17, 18, 20. 
function ModularScenery.Theming__Update__FalloffRadius(SceneryPartName, FalloffRadius)
    DatabaseUtils.ExecuteQuery("ModularScenery", "Theming__Update__FalloffRadius", {SceneryPartName, FalloffRadius}, 2)
end

--- Note: Autogenerated.
--- Inserter for table TriggerTargetProps.
---@param SceneryPartName string Common Values = "AQ_CargoLift", "AQ_Doors_Anim_01", "AQ_Doors_Anim_02", "AQ_FishBeastie", "AQ_SingingEels_Group". 
---@param CostPerTrigger integer Common Values = 0, 200, 500, 600, 400. 
---@param TriggerRunTime number Common Values = 0.0. 
function ModularScenery.TriggerTargetProps__Insert(SceneryPartName, CostPerTrigger, TriggerRunTime)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TriggerTargetProps__Insert", {SceneryPartName, CostPerTrigger, TriggerRunTime}, 3)
end

--- Note: Autogenerated.
--- Updates field "CostPerTrigger" in TriggerTargetProps. Common Values = 0, 200, 500, 600, 400. 
---@param SceneryPartName string Common Values = "AQ_CargoLift", "AQ_Doors_Anim_01", "AQ_Doors_Anim_02", "AQ_FishBeastie", "AQ_SingingEels_Group".  (Lookup Key)
---@param CostPerTrigger integer Common Values = 0, 200, 500, 600, 400. 
function ModularScenery.TriggerTargetProps__Update__CostPerTrigger(SceneryPartName, CostPerTrigger)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TriggerTargetProps__Update__CostPerTrigger", {SceneryPartName, CostPerTrigger}, 2)
end

--- Note: Autogenerated.
--- Updates field "TriggerRunTime" in TriggerTargetProps. Common Values = 0.0. 
---@param SceneryPartName string Common Values = "AQ_CargoLift", "AQ_Doors_Anim_01", "AQ_Doors_Anim_02", "AQ_FishBeastie", "AQ_SingingEels_Group".  (Lookup Key)
---@param TriggerRunTime number Common Values = 0.0. 
function ModularScenery.TriggerTargetProps__Update__TriggerRunTime(SceneryPartName, TriggerRunTime)
    DatabaseUtils.ExecuteQuery("ModularScenery", "TriggerTargetProps__Update__TriggerRunTime", {SceneryPartName, TriggerRunTime}, 2)
end

--- Note: Autogenerated.
--- Inserter for table UIData.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
---@param LabelTextSymbol string Common Values = "BuildingPartName_AQ_Wall_Bevelled_GableTri_2m", "BuildingPartName_AQ_Anchor", "BuildingPartName_AQ_Bench_01", "BuildingPartName_AQ_Bench_02", "BuildingPartName_AQ_Bin_01". 
---@param DescriptionTextSymbol string Common Values = "BuildingPartDesc_SnapEdge", "BuildingPartDesc_AQ_Wall_Bevelled_GableTri_2m", "BuildingPartDesc_AQ_Anchor", "BuildingPartDesc_AQ_Bench_01", "BuildingPartDesc_AQ_Bench_02". 
function ModularScenery.UIData__Insert(SceneryPartName, LabelTextSymbol, DescriptionTextSymbol)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UIData__Insert", {SceneryPartName, LabelTextSymbol, DescriptionTextSymbol}, 3)
end

--- Note: Autogenerated.
--- Updates field "LabelTextSymbol" in UIData. Common Values = "BuildingPartName_AQ_Wall_Bevelled_GableTri_2m", "BuildingPartName_AQ_Anchor", "BuildingPartName_AQ_Bench_01", "BuildingPartName_AQ_Bench_02", "BuildingPartName_AQ_Bin_01". 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param LabelTextSymbol string Common Values = "BuildingPartName_AQ_Wall_Bevelled_GableTri_2m", "BuildingPartName_AQ_Anchor", "BuildingPartName_AQ_Bench_01", "BuildingPartName_AQ_Bench_02", "BuildingPartName_AQ_Bin_01". 
function ModularScenery.UIData__Update__LabelTextSymbol(SceneryPartName, LabelTextSymbol)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UIData__Update__LabelTextSymbol", {SceneryPartName, LabelTextSymbol}, 2)
end

--- Note: Autogenerated.
--- Updates field "DescriptionTextSymbol" in UIData. Common Values = "BuildingPartDesc_SnapEdge", "BuildingPartDesc_AQ_Wall_Bevelled_GableTri_2m", "BuildingPartDesc_AQ_Anchor", "BuildingPartDesc_AQ_Bench_01", "BuildingPartDesc_AQ_Bench_02". 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param DescriptionTextSymbol string Common Values = "BuildingPartDesc_SnapEdge", "BuildingPartDesc_AQ_Wall_Bevelled_GableTri_2m", "BuildingPartDesc_AQ_Anchor", "BuildingPartDesc_AQ_Bench_01", "BuildingPartDesc_AQ_Bench_02". 
function ModularScenery.UIData__Update__DescriptionTextSymbol(SceneryPartName, DescriptionTextSymbol)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UIData__Update__DescriptionTextSymbol", {SceneryPartName, DescriptionTextSymbol}, 2)
end

--- Note: Autogenerated.
--- Updates field "Icon" in UIData. Common Values = nil, "PC_Light_02", "PE_MainGate", "ParkEntrance". 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param Icon string|nil Common Values = nil, "PC_Light_02", "PE_MainGate", "ParkEntrance". 
function ModularScenery.UIData__Update__Icon(SceneryPartName, Icon)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UIData__Update__Icon", {SceneryPartName, Icon}, 2)
end

--- Note: Autogenerated.
--- Updates field "ReleaseGroup" in UIData. Default = "7". Common Values = 0, 6, 3, 5, 1. 
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02".  (Lookup Key)
---@param ReleaseGroup string Default = "7". Common Values = 0, 6, 3, 5, 1. 
function ModularScenery.UIData__Update__ReleaseGroup(SceneryPartName, ReleaseGroup)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UIData__Update__ReleaseGroup", {SceneryPartName, ReleaseGroup}, 2)
end

--- Note: Autogenerated.
--- Inserter for table UIPartOrdering.
---@param DataPrefabName string Common Values = "Facility", "Firework", "Lifeguard", "OnGrid", "ParkEntrance". 
function ModularScenery.UIPartOrdering__Insert(DataPrefabName)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UIPartOrdering__Insert", {DataPrefabName}, 1)
end

--- Note: Autogenerated.
--- Updates field "OrderingValue" in UIPartOrdering. Default = "0". Common Values = 0, 1, 2, 3, 4. 
---@param DataPrefabName string Common Values = "Facility", "Firework", "Lifeguard", "OnGrid", "ParkEntrance".  (Lookup Key)
---@param OrderingValue integer Default = "0". Common Values = 0, 1, 2, 3, 4. 
function ModularScenery.UIPartOrdering__Update__OrderingValue(DataPrefabName, OrderingValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UIPartOrdering__Update__OrderingValue", {DataPrefabName, OrderingValue}, 2)
end

--- Note: Autogenerated.
--- Inserter for table UtilityConnection.
---@param SceneryPartName string Common Values = "Utility_PowerCable", "Utility_PowerCable_Demolish", "Utility_WaterPipe", "Utility_WaterPipe_Demolish". 
---@param UtilityType string Common Values = "Power", "Water". 
---@param CostPerMeter number Common Values = 0.0, 400.0. 
function ModularScenery.UtilityConnection__Insert(SceneryPartName, UtilityType, CostPerMeter)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityConnection__Insert", {SceneryPartName, UtilityType, CostPerMeter}, 3)
end

--- Note: Autogenerated.
--- Updates field "UtilityType" in UtilityConnection. Common Values = "Power", "Water". 
---@param SceneryPartName string Common Values = "Utility_PowerCable", "Utility_PowerCable_Demolish", "Utility_WaterPipe", "Utility_WaterPipe_Demolish".  (Lookup Key)
---@param UtilityType string Common Values = "Power", "Water". 
function ModularScenery.UtilityConnection__Update__UtilityType(SceneryPartName, UtilityType)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityConnection__Update__UtilityType", {SceneryPartName, UtilityType}, 2)
end

--- Note: Autogenerated.
--- Updates field "CostPerMeter" in UtilityConnection. Common Values = 0.0, 400.0. 
---@param SceneryPartName string Common Values = "Utility_PowerCable", "Utility_PowerCable_Demolish", "Utility_WaterPipe", "Utility_WaterPipe_Demolish".  (Lookup Key)
---@param CostPerMeter number Common Values = 0.0, 400.0. 
function ModularScenery.UtilityConnection__Update__CostPerMeter(SceneryPartName, CostPerMeter)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityConnection__Update__CostPerMeter", {SceneryPartName, CostPerMeter}, 2)
end

--- Note: Autogenerated.
--- Inserter for table UtilityConsumer.
---@param SceneryPartName string Common Values = "Facility_HaystackDryer_Standard", "Facility_Heater_Radiant", "Facility_Heater_Wall", "Facility_Restaurant_Kitchen", "Facility_Shops_ChiefBeef". 
---@param UtilityType string Common Values = "Power". 
---@param RequiredUtilityQuantity number Common Values = 5.0, 1.0, 2.0, 10.0, 15.0. 
function ModularScenery.UtilityConsumer__Insert(SceneryPartName, UtilityType, RequiredUtilityQuantity)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityConsumer__Insert", {SceneryPartName, UtilityType, RequiredUtilityQuantity}, 3)
end

--- Note: Autogenerated.
--- Updates field "RequiredUtilityQuantity" in UtilityConsumer. Common Values = 5.0, 1.0, 2.0, 10.0, 15.0. 
---@param SceneryPartName string Common Values = "Facility_HaystackDryer_Standard", "Facility_Heater_Radiant", "Facility_Heater_Wall", "Facility_Restaurant_Kitchen", "Facility_Shops_ChiefBeef".  (Lookup Key)
---@param UtilityType string Common Values = "Power".  (Lookup Key)
---@param RequiredUtilityQuantity number Common Values = 5.0, 1.0, 2.0, 10.0, 15.0. 
function ModularScenery.UtilityConsumer__Update__RequiredUtilityQuantity(SceneryPartName, UtilityType, RequiredUtilityQuantity)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityConsumer__Update__RequiredUtilityQuantity", {SceneryPartName, UtilityType, RequiredUtilityQuantity}, 3)
end

--- Note: Autogenerated.
--- Inserter for table UtilityDistribution.
---@param SceneryPartName string Common Values = "Utility_PowerDistributor_Standard", "Utility_WaterDistributor_Small_Standard", "Utility_WaterDistributor_Standard". 
---@param UtilityType string Common Values = "Water", "Power". 
---@param RateOfTransfer number Common Values = 10.0. 
---@param RadiusOfEffect number Common Values = 40.0, 70.0. 
function ModularScenery.UtilityDistribution__Insert(SceneryPartName, UtilityType, RateOfTransfer, RadiusOfEffect)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityDistribution__Insert", {SceneryPartName, UtilityType, RateOfTransfer, RadiusOfEffect}, 4)
end

--- Note: Autogenerated.
--- Updates field "UtilityType" in UtilityDistribution. Common Values = "Water", "Power". 
---@param SceneryPartName string Common Values = "Utility_PowerDistributor_Standard", "Utility_WaterDistributor_Small_Standard", "Utility_WaterDistributor_Standard".  (Lookup Key)
---@param UtilityType string Common Values = "Water", "Power". 
function ModularScenery.UtilityDistribution__Update__UtilityType(SceneryPartName, UtilityType)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityDistribution__Update__UtilityType", {SceneryPartName, UtilityType}, 2)
end

--- Note: Autogenerated.
--- Updates field "RateOfTransfer" in UtilityDistribution. Common Values = 10.0. 
---@param SceneryPartName string Common Values = "Utility_PowerDistributor_Standard", "Utility_WaterDistributor_Small_Standard", "Utility_WaterDistributor_Standard".  (Lookup Key)
---@param RateOfTransfer number Common Values = 10.0. 
function ModularScenery.UtilityDistribution__Update__RateOfTransfer(SceneryPartName, RateOfTransfer)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityDistribution__Update__RateOfTransfer", {SceneryPartName, RateOfTransfer}, 2)
end

--- Note: Autogenerated.
--- Updates field "RadiusOfEffect" in UtilityDistribution. Common Values = 40.0, 70.0. 
---@param SceneryPartName string Common Values = "Utility_PowerDistributor_Standard", "Utility_WaterDistributor_Small_Standard", "Utility_WaterDistributor_Standard".  (Lookup Key)
---@param RadiusOfEffect number Common Values = 40.0, 70.0. 
function ModularScenery.UtilityDistribution__Update__RadiusOfEffect(SceneryPartName, RadiusOfEffect)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityDistribution__Update__RadiusOfEffect", {SceneryPartName, RadiusOfEffect}, 2)
end

--- Note: Autogenerated.
--- Inserter for table UtilityProduction.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". 
---@param UtilityType string Common Values = "Power", "Water". 
---@param ProductionPerHour number Common Values = 60.0, 120.0, 80.0, 240.0, 300.0. 
---@param CostPerUtilityPerHour number Common Values = 0.0, 80.0, 160.0, 300.0, 440.0. 
---@param TotalBreakdownTimeMinutes number Common Values = 220.0, 0.0, 290.0. 
---@param ServiceCostPerPct integer Common Values = 600, 0, 400, 1750. 
---@param EfficiencyRespite number Common Values = 0.7, 1.0. 
function ModularScenery.UtilityProduction__Insert(SceneryPartName, UtilityType, ProductionPerHour, CostPerUtilityPerHour, TotalBreakdownTimeMinutes, ServiceCostPerPct, EfficiencyRespite)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityProduction__Insert", {SceneryPartName, UtilityType, ProductionPerHour, CostPerUtilityPerHour, TotalBreakdownTimeMinutes, ServiceCostPerPct, EfficiencyRespite}, 7)
end

--- Note: Autogenerated.
--- Updates field "ProductionPerHour" in UtilityProduction. Common Values = 60.0, 120.0, 80.0, 240.0, 300.0. 
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower".  (Lookup Key)
---@param UtilityType string Common Values = "Power", "Water".  (Lookup Key)
---@param ProductionPerHour number Common Values = 60.0, 120.0, 80.0, 240.0, 300.0. 
function ModularScenery.UtilityProduction__Update__ProductionPerHour(SceneryPartName, UtilityType, ProductionPerHour)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityProduction__Update__ProductionPerHour", {SceneryPartName, UtilityType, ProductionPerHour}, 3)
end

--- Note: Autogenerated.
--- Updates field "CostPerUtilityPerHour" in UtilityProduction. Common Values = 0.0, 80.0, 160.0, 300.0, 440.0. 
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower".  (Lookup Key)
---@param UtilityType string Common Values = "Power", "Water".  (Lookup Key)
---@param CostPerUtilityPerHour number Common Values = 0.0, 80.0, 160.0, 300.0, 440.0. 
function ModularScenery.UtilityProduction__Update__CostPerUtilityPerHour(SceneryPartName, UtilityType, CostPerUtilityPerHour)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityProduction__Update__CostPerUtilityPerHour", {SceneryPartName, UtilityType, CostPerUtilityPerHour}, 3)
end

--- Note: Autogenerated.
--- Updates field "TotalBreakdownTimeMinutes" in UtilityProduction. Common Values = 220.0, 0.0, 290.0. 
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower".  (Lookup Key)
---@param UtilityType string Common Values = "Power", "Water".  (Lookup Key)
---@param TotalBreakdownTimeMinutes number Common Values = 220.0, 0.0, 290.0. 
function ModularScenery.UtilityProduction__Update__TotalBreakdownTimeMinutes(SceneryPartName, UtilityType, TotalBreakdownTimeMinutes)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityProduction__Update__TotalBreakdownTimeMinutes", {SceneryPartName, UtilityType, TotalBreakdownTimeMinutes}, 3)
end

--- Note: Autogenerated.
--- Updates field "ServiceCostPerPct" in UtilityProduction. Common Values = 600, 0, 400, 1750. 
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower".  (Lookup Key)
---@param UtilityType string Common Values = "Power", "Water".  (Lookup Key)
---@param ServiceCostPerPct integer Common Values = 600, 0, 400, 1750. 
function ModularScenery.UtilityProduction__Update__ServiceCostPerPct(SceneryPartName, UtilityType, ServiceCostPerPct)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityProduction__Update__ServiceCostPerPct", {SceneryPartName, UtilityType, ServiceCostPerPct}, 3)
end

--- Note: Autogenerated.
--- Updates field "EfficiencyRespite" in UtilityProduction. Common Values = 0.7, 1.0. 
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower".  (Lookup Key)
---@param UtilityType string Common Values = "Power", "Water".  (Lookup Key)
---@param EfficiencyRespite number Common Values = 0.7, 1.0. 
function ModularScenery.UtilityProduction__Update__EfficiencyRespite(SceneryPartName, UtilityType, EfficiencyRespite)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityProduction__Update__EfficiencyRespite", {SceneryPartName, UtilityType, EfficiencyRespite}, 3)
end

--- Note: Autogenerated.
--- Inserter for table UtilityTypes.
---@param UtilityType string Common Values = "None", "Power", "Water". 
---@param EnumValue integer Common Values = 0, 1, 2. 
function ModularScenery.UtilityTypes__Insert(UtilityType, EnumValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityTypes__Insert", {UtilityType, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Updates field "EnumValue" in UtilityTypes. Common Values = 0, 1, 2. 
---@param UtilityType string Common Values = "None", "Power", "Water".  (Lookup Key)
---@param EnumValue integer Common Values = 0, 1, 2. 
function ModularScenery.UtilityTypes__Update__EnumValue(UtilityType, EnumValue)
    DatabaseUtils.ExecuteQuery("ModularScenery", "UtilityTypes__Update__EnumValue", {UtilityType, EnumValue}, 2)
end

--- Note: Autogenerated.
--- Inserter for table WaterCleanliness.
---@param WaterConsumerType string Common Values = "ClothedRide", "Pool", "SwimsuitRide", "Toilets". 
---@param WaterConsumerEnum integer Common Values = 0, 1, 2, 3. 
---@param CleanlinessScalar number Common Values = 0.125, 0.166, 0.5, 1.0. 
---@param VolumeMultiplier number Common Values = 0.1, 1.5. 
function ModularScenery.WaterCleanliness__Insert(WaterConsumerType, WaterConsumerEnum, CleanlinessScalar, VolumeMultiplier)
    DatabaseUtils.ExecuteQuery("ModularScenery", "WaterCleanliness__Insert", {WaterConsumerType, WaterConsumerEnum, CleanlinessScalar, VolumeMultiplier}, 4)
end

--- Note: Autogenerated.
--- Updates field "WaterConsumerEnum" in WaterCleanliness. Common Values = 0, 1, 2, 3. 
---@param WaterConsumerType string Common Values = "ClothedRide", "Pool", "SwimsuitRide", "Toilets".  (Lookup Key)
---@param WaterConsumerEnum integer Common Values = 0, 1, 2, 3. 
function ModularScenery.WaterCleanliness__Update__WaterConsumerEnum(WaterConsumerType, WaterConsumerEnum)
    DatabaseUtils.ExecuteQuery("ModularScenery", "WaterCleanliness__Update__WaterConsumerEnum", {WaterConsumerType, WaterConsumerEnum}, 2)
end

--- Note: Autogenerated.
--- Updates field "CleanlinessScalar" in WaterCleanliness. Common Values = 0.125, 0.166, 0.5, 1.0. 
---@param WaterConsumerType string Common Values = "ClothedRide", "Pool", "SwimsuitRide", "Toilets".  (Lookup Key)
---@param CleanlinessScalar number Common Values = 0.125, 0.166, 0.5, 1.0. 
function ModularScenery.WaterCleanliness__Update__CleanlinessScalar(WaterConsumerType, CleanlinessScalar)
    DatabaseUtils.ExecuteQuery("ModularScenery", "WaterCleanliness__Update__CleanlinessScalar", {WaterConsumerType, CleanlinessScalar}, 2)
end

--- Note: Autogenerated.
--- Updates field "VolumeMultiplier" in WaterCleanliness. Common Values = 0.1, 1.5. 
---@param WaterConsumerType string Common Values = "ClothedRide", "Pool", "SwimsuitRide", "Toilets".  (Lookup Key)
---@param VolumeMultiplier number Common Values = 0.1, 1.5. 
function ModularScenery.WaterCleanliness__Update__VolumeMultiplier(WaterConsumerType, VolumeMultiplier)
    DatabaseUtils.ExecuteQuery("ModularScenery", "WaterCleanliness__Update__VolumeMultiplier", {WaterConsumerType, VolumeMultiplier}, 2)
end


return ModularScenery
