---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE EXT FOLDER.
--- 
local global = _G
local ipairs = global.ipairs
local DatabaseUtils = require("forgeutils.internal.database.databaseutils")

local logger = require("forgeutils.logger").Get("TrackedRideCars")

---@class forgeutils.internal.database.TrackedRideCars
--- Note: Autogenerated!
--- This is a generated lua binding layer for the TrackedRideCars database.
local TrackedRideCars = {}

---@private
--- This method is called after data is merged
TrackedRideCars.InsertToDBs = function()
    TrackedRideCars.BindPreparedStatements()
end

TrackedRideCars.tPreparedStatements = {
    "TrackedRideCars_Cars", 
    "TrackedRideCars_CatchTrains", 
    "TrackedRideCars_RacingTrains", 
    "TrackedRideCars_Trains", 
    "TrackedRideCars_TransitionList", 
    "TrackedRideCars_WhichCar"
}

---@private
function TrackedRideCars.BindPreparedStatements()
    logger:DebugQuery("BindPreparedStatements()")
    for _, filename in ipairs(TrackedRideCars.tPreparedStatements) do
        DatabaseUtils.BindPreparedStatement("TrackedRideCars", filename)
    end
end


--- Note: Autogenerated.
--- Inserter for table Cars.
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster". 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". 
---@param Mass number Common Values = 100.0, 140.0, 700.0, 1200.0, 800.0. 
function TrackedRideCars.Cars__Insert(TrainID, CarID, Mass)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Insert", {TrainID, CarID, Mass}, 3)
end

--- Note: Autogenerated.
--- Updates field "TrainID" in Cars. Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster". 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster". 
function TrackedRideCars.Cars__Update__TrainID(CarID, TrainID)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__TrainID", {CarID, TrainID}, 2)
end

--- Note: Autogenerated.
--- Updates field "WhichCar" in Cars. Common Values = "Front", "Middle", "Rear". 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param WhichCar string|nil Common Values = "Front", "Middle", "Rear". 
function TrackedRideCars.Cars__Update__WhichCar(CarID, WhichCar)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__WhichCar", {CarID, WhichCar}, 2)
end

--- Note: Autogenerated.
--- Updates field "CarOrder" in Cars. Default = "0". Common Values = 0, 1, 2, 3, 4. 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param CarOrder integer|nil Default = "0". Common Values = 0, 1, 2, 3, 4. 
function TrackedRideCars.Cars__Update__CarOrder(CarID, CarOrder)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__CarOrder", {CarID, CarOrder}, 2)
end

--- Note: Autogenerated.
--- Updates field "Prefab" in Cars. Common Values = "CC_BakasuraCarF_Art", "TR_GondolaCarF_Game", "BodyFlumeCarF_Art", "BodySlideCarF_Art", "CC_AethonCarF_Art". 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param Prefab string|nil Common Values = "CC_BakasuraCarF_Art", "TR_GondolaCarF_Game", "BodyFlumeCarF_Art", "BodySlideCarF_Art", "CC_AethonCarF_Art". 
function TrackedRideCars.Cars__Update__Prefab(CarID, Prefab)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__Prefab", {CarID, Prefab}, 2)
end

--- Note: Autogenerated.
--- Updates field "Mass" in Cars. Common Values = 100.0, 140.0, 700.0, 1200.0, 800.0. 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param Mass number Common Values = 100.0, 140.0, 700.0, 1200.0, 800.0. 
function TrackedRideCars.Cars__Update__Mass(CarID, Mass)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__Mass", {CarID, Mass}, 2)
end

--- Note: Autogenerated.
--- Updates field "PlatformPrefab" in Cars. Common Values = nil, "StationPlatform_CC_Stingray_Front", "StationPlatform_CC_Stingray_Mid", "StationPlatform_CC_Stingray_Rear", "StationPlatform_CC_Aethon_Front". 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param PlatformPrefab string|nil Common Values = nil, "StationPlatform_CC_Stingray_Front", "StationPlatform_CC_Stingray_Mid", "StationPlatform_CC_Stingray_Rear", "StationPlatform_CC_Aethon_Front". 
function TrackedRideCars.Cars__Update__PlatformPrefab(CarID, PlatformPrefab)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__PlatformPrefab", {CarID, PlatformPrefab}, 2)
end

--- Note: Autogenerated.
--- Updates field "IsPowered" in Cars. Default = "0". Common Values = 0, 1. 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param IsPowered boolean|nil Default = "0". Common Values = 0, 1. 
function TrackedRideCars.Cars__Update__IsPowered(CarID, IsPowered)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__IsPowered", {CarID, IsPowered}, 2)
end

--- Note: Autogenerated.
--- Inserter for table CatchTrains.
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar". 
function TrackedRideCars.CatchTrains__Insert(TrainID)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Insert", {TrainID}, 1)
end

--- Note: Autogenerated.
--- Updates field "ShouldWait" in CatchTrains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar".  (Lookup Key)
---@param ShouldWait boolean Default = "0". Common Values = 0, 1. 
function TrackedRideCars.CatchTrains__Update__ShouldWait(TrainID, ShouldWait)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Update__ShouldWait", {TrainID, ShouldWait}, 2)
end

--- Note: Autogenerated.
--- Updates field "CatchOnReturn" in CatchTrains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar".  (Lookup Key)
---@param CatchOnReturn boolean Default = "0". Common Values = 0, 1. 
function TrackedRideCars.CatchTrains__Update__CatchOnReturn(TrainID, CatchOnReturn)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Update__CatchOnReturn", {TrainID, CatchOnReturn}, 2)
end

--- Note: Autogenerated.
--- Updates field "MatchSpeed" in CatchTrains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar".  (Lookup Key)
---@param MatchSpeed boolean Default = "0". Common Values = 0, 1. 
function TrackedRideCars.CatchTrains__Update__MatchSpeed(TrainID, MatchSpeed)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Update__MatchSpeed", {TrainID, MatchSpeed}, 2)
end

--- Note: Autogenerated.
--- Updates field "CatchOnFinalLap" in CatchTrains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar".  (Lookup Key)
---@param CatchOnFinalLap boolean Default = "0". Common Values = 0, 1. 
function TrackedRideCars.CatchTrains__Update__CatchOnFinalLap(TrainID, CatchOnFinalLap)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Update__CatchOnFinalLap", {TrainID, CatchOnFinalLap}, 2)
end

--- Note: Autogenerated.
--- Inserter for table RacingTrains.
---@param TrainID string Common Values = "Speed". 
function TrackedRideCars.RacingTrains__Insert(TrainID)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Insert", {TrainID}, 1)
end

--- Note: Autogenerated.
--- Updates field "PitOffset" in RacingTrains. Common Values = 5.067. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param PitOffset number|nil Common Values = 5.067. 
function TrackedRideCars.RacingTrains__Update__PitOffset(TrainID, PitOffset)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__PitOffset", {TrainID, PitOffset}, 2)
end

--- Note: Autogenerated.
--- Updates field "PitFront" in RacingTrains. Common Values = 7.0. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param PitFront number|nil Common Values = 7.0. 
function TrackedRideCars.RacingTrains__Update__PitFront(TrainID, PitFront)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__PitFront", {TrainID, PitFront}, 2)
end

--- Note: Autogenerated.
--- Updates field "PitStep" in RacingTrains. Common Values = 4.5. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param PitStep number|nil Common Values = 4.5. 
function TrackedRideCars.RacingTrains__Update__PitStep(TrainID, PitStep)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__PitStep", {TrainID, PitStep}, 2)
end

--- Note: Autogenerated.
--- Updates field "StartingOffset" in RacingTrains. Common Values = 1.8. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param StartingOffset number|nil Common Values = 1.8. 
function TrackedRideCars.RacingTrains__Update__StartingOffset(TrainID, StartingOffset)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__StartingOffset", {TrainID, StartingOffset}, 2)
end

--- Note: Autogenerated.
--- Updates field "StartingFront" in RacingTrains. Common Values = 3.5. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param StartingFront number|nil Common Values = 3.5. 
function TrackedRideCars.RacingTrains__Update__StartingFront(TrainID, StartingFront)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__StartingFront", {TrainID, StartingFront}, 2)
end

--- Note: Autogenerated.
--- Updates field "StartingStep" in RacingTrains. Common Values = 4.4. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param StartingStep number|nil Common Values = 4.4. 
function TrackedRideCars.RacingTrains__Update__StartingStep(TrainID, StartingStep)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__StartingStep", {TrainID, StartingStep}, 2)
end

--- Note: Autogenerated.
--- Inserter for table Trains.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". 
---@param CanAddOffStation boolean Common Values = 0, 1. 
function TrackedRideCars.Trains__Insert(TrainID, CanAddOffStation)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Insert", {TrainID, CanAddOffStation}, 2)
end

--- Note: Autogenerated.
--- Updates field "StaticFriction" in Trains. Default = "0.06". Common Values = 0.06, 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param StaticFriction number|nil Default = "0.06". Common Values = 0.06, 0.0. 
function TrackedRideCars.Trains__Update__StaticFriction(TrainID, StaticFriction)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__StaticFriction", {TrainID, StaticFriction}, 2)
end

--- Note: Autogenerated.
--- Updates field "AirResistance" in Trains. Default = "0.02". Common Values = 0.02, 0.4, 0.04, 0.36, 0.39. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AirResistance number|nil Default = "0.02". Common Values = 0.02, 0.4, 0.04, 0.36, 0.39. 
function TrackedRideCars.Trains__Update__AirResistance(TrainID, AirResistance)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AirResistance", {TrainID, AirResistance}, 2)
end

--- Note: Autogenerated.
--- Updates field "DynamicFriction" in Trains. Default = "0.04". Common Values = 0.03, 0.035, 0.039, 0.04, 0.08. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param DynamicFriction number|nil Default = "0.04". Common Values = 0.03, 0.035, 0.039, 0.04, 0.08. 
function TrackedRideCars.Trains__Update__DynamicFriction(TrainID, DynamicFriction)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__DynamicFriction", {TrainID, DynamicFriction}, 2)
end

--- Note: Autogenerated.
--- Updates field "DynamicFriction_Alternate" in Trains. Common Values = nil, 0.6, 0.11, 0.05, "". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param DynamicFriction_Alternate number|nil Common Values = nil, 0.6, 0.11, 0.05, "". 
function TrackedRideCars.Trains__Update__DynamicFriction_Alternate(TrainID, DynamicFriction_Alternate)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__DynamicFriction_Alternate", {TrainID, DynamicFriction_Alternate}, 2)
end

--- Note: Autogenerated.
--- Updates field "LuaScoringModule" in Trains. Default = "DefaultScoring". Common Values = "CoasterScoring", "NonInvertedCoasterScoring", "DefaultScoring", "SwimsuitFlumeScoring", "CascadeScoring". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param LuaScoringModule string|nil Default = "DefaultScoring". Common Values = "CoasterScoring", "NonInvertedCoasterScoring", "DefaultScoring", "SwimsuitFlumeScoring", "CascadeScoring". 
function TrackedRideCars.Trains__Update__LuaScoringModule(TrainID, LuaScoringModule)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__LuaScoringModule", {TrainID, LuaScoringModule}, 2)
end

--- Note: Autogenerated.
--- Updates field "BaseExcitement" in Trains. Common Values = nil, 4.0, 3.0, 4.5, 6.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param BaseExcitement number|nil Common Values = nil, 4.0, 3.0, 4.5, 6.0. 
function TrackedRideCars.Trains__Update__BaseExcitement(TrainID, BaseExcitement)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__BaseExcitement", {TrainID, BaseExcitement}, 2)
end

--- Note: Autogenerated.
--- Updates field "BaseFear" in Trains. Common Values = nil, 2.0, 1.0, 2.5, "". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param BaseFear number|nil Common Values = nil, 2.0, 1.0, 2.5, "". 
function TrackedRideCars.Trains__Update__BaseFear(TrainID, BaseFear)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__BaseFear", {TrainID, BaseFear}, 2)
end

--- Note: Autogenerated.
--- Updates field "BaseNausea" in Trains. Common Values = nil, 1.0, "". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param BaseNausea number|nil Common Values = nil, 1.0, "". 
function TrackedRideCars.Trains__Update__BaseNausea(TrainID, BaseNausea)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__BaseNausea", {TrainID, BaseNausea}, 2)
end

--- Note: Autogenerated.
--- Updates field "CanAddOffStation" in Trains. Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param CanAddOffStation boolean Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__CanAddOffStation(TrainID, CanAddOffStation)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__CanAddOffStation", {TrainID, CanAddOffStation}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioSpeedThreshold" in Trains. Default = "25". Common Values = 25.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioSpeedThreshold number|nil Default = "25". Common Values = 25.0. 
function TrackedRideCars.Trains__Update__AudioSpeedThreshold(TrainID, AudioSpeedThreshold)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioSpeedThreshold", {TrainID, AudioSpeedThreshold}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioAccnThreshold" in Trains. Default = "30". Common Values = 30.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioAccnThreshold number|nil Default = "30". Common Values = 30.0. 
function TrackedRideCars.Trains__Update__AudioAccnThreshold(TrainID, AudioAccnThreshold)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioAccnThreshold", {TrainID, AudioAccnThreshold}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioWeightThreshold" in Trains. Default = "100". Common Values = 100.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioWeightThreshold number|nil Default = "100". Common Values = 100.0. 
function TrackedRideCars.Trains__Update__AudioWeightThreshold(TrainID, AudioWeightThreshold)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioWeightThreshold", {TrainID, AudioWeightThreshold}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioLateralThreshold" in Trains. Default = "50". Common Values = 50.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioLateralThreshold number|nil Default = "50". Common Values = 50.0. 
function TrackedRideCars.Trains__Update__AudioLateralThreshold(TrainID, AudioLateralThreshold)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioLateralThreshold", {TrainID, AudioLateralThreshold}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioUseFrontAxelForFlanges" in Trains. Default = "0". Common Values = 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioUseFrontAxelForFlanges number|nil Default = "0". Common Values = 0.0. 
function TrackedRideCars.Trains__Update__AudioUseFrontAxelForFlanges(TrainID, AudioUseFrontAxelForFlanges)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioUseFrontAxelForFlanges", {TrainID, AudioUseFrontAxelForFlanges}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioIgnoreFrontCarForFlanges" in Trains. Default = "0". Common Values = 0.0, 1.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioIgnoreFrontCarForFlanges number|nil Default = "0". Common Values = 0.0, 1.0. 
function TrackedRideCars.Trains__Update__AudioIgnoreFrontCarForFlanges(TrainID, AudioIgnoreFrontCarForFlanges)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioIgnoreFrontCarForFlanges", {TrainID, AudioIgnoreFrontCarForFlanges}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioIgnoreRearCarForFlanges" in Trains. Default = "1". Common Values = 1.0, 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioIgnoreRearCarForFlanges number|nil Default = "1". Common Values = 1.0, 0.0. 
function TrackedRideCars.Trains__Update__AudioIgnoreRearCarForFlanges(TrainID, AudioIgnoreRearCarForFlanges)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioIgnoreRearCarForFlanges", {TrainID, AudioIgnoreRearCarForFlanges}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioIgnoreMidCarsForFlanges" in Trains. Default = "1". Common Values = 1.0, 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioIgnoreMidCarsForFlanges number|nil Default = "1". Common Values = 1.0, 0.0. 
function TrackedRideCars.Trains__Update__AudioIgnoreMidCarsForFlanges(TrainID, AudioIgnoreMidCarsForFlanges)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioIgnoreMidCarsForFlanges", {TrainID, AudioIgnoreMidCarsForFlanges}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioChainLiftPrefix" in Trains. Default = "CL". Common Values = "Mtl", "FWL", "SlideConveyor", "Wood", "Hyb". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioChainLiftPrefix string|nil Default = "CL". Common Values = "Mtl", "FWL", "SlideConveyor", "Wood", "Hyb". 
function TrackedRideCars.Trains__Update__AudioChainLiftPrefix(TrainID, AudioChainLiftPrefix)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioChainLiftPrefix", {TrainID, AudioChainLiftPrefix}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioBrakePrefix" in Trains. Default = "Fri". Common Values = "Fri", "Mag", "SlideBrake", "SFri", "WdFr". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioBrakePrefix string|nil Default = "Fri". Common Values = "Fri", "Mag", "SlideBrake", "SFri", "WdFr". 
function TrackedRideCars.Trains__Update__AudioBrakePrefix(TrainID, AudioBrakePrefix)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioBrakePrefix", {TrainID, AudioBrakePrefix}, 2)
end

--- Note: Autogenerated.
--- Updates field "DefaultRideMusic" in Trains. Default = "NO_MUSIC". Common Values = "NO_MUSIC", "GondolaLift_TRMusic". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param DefaultRideMusic string|nil Default = "NO_MUSIC". Common Values = "NO_MUSIC", "GondolaLift_TRMusic". 
function TrackedRideCars.Trains__Update__DefaultRideMusic(TrainID, DefaultRideMusic)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__DefaultRideMusic", {TrainID, DefaultRideMusic}, 2)
end

--- Note: Autogenerated.
--- Updates field "UniqueEngineSound" in Trains. Default = "0". Common Values = 0.0, 1.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param UniqueEngineSound number|nil Default = "0". Common Values = 0.0, 1.0. 
function TrackedRideCars.Trains__Update__UniqueEngineSound(TrainID, UniqueEngineSound)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__UniqueEngineSound", {TrainID, UniqueEngineSound}, 2)
end

--- Note: Autogenerated.
--- Updates field "PlayMusicContinuously" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param PlayMusicContinuously boolean|nil Default = "0". Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__PlayMusicContinuously(TrainID, PlayMusicContinuously)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__PlayMusicContinuously", {TrainID, PlayMusicContinuously}, 2)
end

--- Note: Autogenerated.
--- Updates field "PlayMusicOnAllCarsSimultaneously" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param PlayMusicOnAllCarsSimultaneously boolean|nil Default = "0". Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__PlayMusicOnAllCarsSimultaneously(TrainID, PlayMusicOnAllCarsSimultaneously)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__PlayMusicOnAllCarsSimultaneously", {TrainID, PlayMusicOnAllCarsSimultaneously}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioGuestsUseExcitement" in Trains. Default = "1". Common Values = 1, 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioGuestsUseExcitement boolean Default = "1". Common Values = 1, 0. 
function TrackedRideCars.Trains__Update__AudioGuestsUseExcitement(TrainID, AudioGuestsUseExcitement)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioGuestsUseExcitement", {TrainID, AudioGuestsUseExcitement}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioGuestsUseFear" in Trains. Default = "1". Common Values = 1, 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioGuestsUseFear boolean Default = "1". Common Values = 1, 0. 
function TrackedRideCars.Trains__Update__AudioGuestsUseFear(TrainID, AudioGuestsUseFear)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioGuestsUseFear", {TrainID, AudioGuestsUseFear}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioGuestsUseSpecialBehaviour" in Trains. Default = "1". Common Values = 1, 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioGuestsUseSpecialBehaviour boolean Default = "1". Common Values = 1, 0. 
function TrackedRideCars.Trains__Update__AudioGuestsUseSpecialBehaviour(TrainID, AudioGuestsUseSpecialBehaviour)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioGuestsUseSpecialBehaviour", {TrainID, AudioGuestsUseSpecialBehaviour}, 2)
end

--- Note: Autogenerated.
--- Updates field "UseTransportRideMusic" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param UseTransportRideMusic boolean Default = "0". Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__UseTransportRideMusic(TrainID, UseTransportRideMusic)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__UseTransportRideMusic", {TrainID, UseTransportRideMusic}, 2)
end

--- Note: Autogenerated.
--- Updates field "TreatAsCoaster" in Trains. Default = "1". Common Values = 1, 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param TreatAsCoaster boolean Default = "1". Common Values = 1, 0. 
function TrackedRideCars.Trains__Update__TreatAsCoaster(TrainID, TreatAsCoaster)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__TreatAsCoaster", {TrainID, TreatAsCoaster}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioMaxRange" in Trains. Default = "500". Common Values = 500.0, 300.0, 35.0, 75.0, 200.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioMaxRange number|nil Default = "500". Common Values = 500.0, 300.0, 35.0, 75.0, 200.0. 
function TrackedRideCars.Trains__Update__AudioMaxRange(TrainID, AudioMaxRange)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioMaxRange", {TrainID, AudioMaxRange}, 2)
end

--- Note: Autogenerated.
--- Updates field "CatchTrainType" in Trains. Common Values = nil, "TK_010_CatchCar", "TK_019_CableHookCar", 0, "TK_010_CableHookCar". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param CatchTrainType string|nil Common Values = nil, "TK_010_CatchCar", "TK_019_CableHookCar", 0, "TK_010_CableHookCar". 
function TrackedRideCars.Trains__Update__CatchTrainType(TrainID, CatchTrainType)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__CatchTrainType", {TrainID, CatchTrainType}, 2)
end

--- Note: Autogenerated.
--- Updates field "NumCatchCars" in Trains. Default = "0". Common Values = 0, 1, 2. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param NumCatchCars integer Default = "0". Common Values = 0, 1, 2. 
function TrackedRideCars.Trains__Update__NumCatchCars(TrainID, NumCatchCars)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__NumCatchCars", {TrainID, NumCatchCars}, 2)
end

--- Note: Autogenerated.
--- Updates field "ReverseCatchTrainType" in Trains. Common Values = nil, "TK_014_CatchCar_001", 0, "TK_015_CatchCar_Rev". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param ReverseCatchTrainType string|nil Common Values = nil, "TK_014_CatchCar_001", 0, "TK_015_CatchCar_Rev". 
function TrackedRideCars.Trains__Update__ReverseCatchTrainType(TrainID, ReverseCatchTrainType)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__ReverseCatchTrainType", {TrainID, ReverseCatchTrainType}, 2)
end

--- Note: Autogenerated.
--- Updates field "NumReverseCatchCars" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param NumReverseCatchCars integer Default = "0". Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__NumReverseCatchCars(TrainID, NumReverseCatchCars)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__NumReverseCatchCars", {TrainID, NumReverseCatchCars}, 2)
end

--- Note: Autogenerated.
--- Updates field "SplitCatchTrainType" in Trains. Common Values = nil, "TK_014_CatchCar_002", 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param SplitCatchTrainType string|nil Common Values = nil, "TK_014_CatchCar_002", 0. 
function TrackedRideCars.Trains__Update__SplitCatchTrainType(TrainID, SplitCatchTrainType)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__SplitCatchTrainType", {TrainID, SplitCatchTrainType}, 2)
end

--- Note: Autogenerated.
--- Updates field "SplitNormalTrainDelay" in Trains. Default = "0". Common Values = 0.0, 3.0, 1.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param SplitNormalTrainDelay number Default = "0". Common Values = 0.0, 3.0, 1.0. 
function TrackedRideCars.Trains__Update__SplitNormalTrainDelay(TrainID, SplitNormalTrainDelay)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__SplitNormalTrainDelay", {TrainID, SplitNormalTrainDelay}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioPrefixOverride" in Trains. Common Values = nil, "BigM_WaterCoaster", "HPC_HybridSteel", "HPC_HybridTopped", "Move_MineTrain". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioPrefixOverride string|nil Common Values = nil, "BigM_WaterCoaster", "HPC_HybridSteel", "HPC_HybridTopped", "Move_MineTrain". 
function TrackedRideCars.Trains__Update__AudioPrefixOverride(TrainID, AudioPrefixOverride)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioPrefixOverride", {TrainID, AudioPrefixOverride}, 2)
end

--- Note: Autogenerated.
--- Updates field "UseMirrorCarRotation" in Trains. Default = "0". Common Values = 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param UseMirrorCarRotation boolean|nil Default = "0". Common Values = 0. 
function TrackedRideCars.Trains__Update__UseMirrorCarRotation(TrainID, UseMirrorCarRotation)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__UseMirrorCarRotation", {TrainID, UseMirrorCarRotation}, 2)
end

--- Note: Autogenerated.
--- Updates field "ForceCarAttachOffsetYToZero" in Trains. Default = "0". Common Values = 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param ForceCarAttachOffsetYToZero boolean|nil Default = "0". Common Values = 0. 
function TrackedRideCars.Trains__Update__ForceCarAttachOffsetYToZero(TrainID, ForceCarAttachOffsetYToZero)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__ForceCarAttachOffsetYToZero", {TrainID, ForceCarAttachOffsetYToZero}, 2)
end

--- Note: Autogenerated.
--- Updates field "ForceCarAttachOffsetYToValue" in Trains. Default = "0". Common Values = 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param ForceCarAttachOffsetYToValue number|nil Default = "0". Common Values = 0.0. 
function TrackedRideCars.Trains__Update__ForceCarAttachOffsetYToValue(TrainID, ForceCarAttachOffsetYToValue)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__ForceCarAttachOffsetYToValue", {TrainID, ForceCarAttachOffsetYToValue}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioCabinIsEnclosed" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioCabinIsEnclosed boolean Default = "0". Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__AudioCabinIsEnclosed(TrainID, AudioCabinIsEnclosed)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioCabinIsEnclosed", {TrainID, AudioCabinIsEnclosed}, 2)
end

--- Note: Autogenerated.
--- Updates field "IsWaterSlideTrain" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param IsWaterSlideTrain integer Default = "0". Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__IsWaterSlideTrain(TrainID, IsWaterSlideTrain)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__IsWaterSlideTrain", {TrainID, IsWaterSlideTrain}, 2)
end

--- Note: Autogenerated.
--- Inserter for table TransitionList.
---@param TrackedRideName string|nil 
function TrackedRideCars.TransitionList__Insert(TrackedRideName)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "TransitionList__Insert", {TrackedRideName}, 1)
end

--- Note: Autogenerated.
--- Inserter for table WhichCar.
---@param ID string Common Values = "Front", "Middle", "Rear". 
function TrackedRideCars.WhichCar__Insert(ID)
    DatabaseUtils.ExecuteQuery("TrackedRideCars", "WhichCar__Insert", {ID}, 1)
end


return TrackedRideCars
